export const MOMENTEN = {
  "HC001": { jaar:1991, cat:"Grote Ronde", renner:"Miguel Induráin", nat:"🇪🇸 Spanje", race:"Tour de France", kort:"Een Spaans klimmer domineert het peloton en rijdt solo naar zijn eerste grote overwinning", lang:"Miguel Induráin schreef geschiedenis door de Tour de France te winnen, zijn eerste van vijf opeenvolgende zeges. Met zijn krachtige zeitritkunsten en bergvaardigheid domineerde hij het peloton volledig. Op de Mont Ventoux reed hij zijn concurrenten in het niets en bevestigde zijn suprematie. Deze overwinning markeerde het begin van het Indurain-era in het wielrennen en legde de basis voor een periode van absolute hegemonie in de koers.", diff:1 },

  "HC002": { jaar:1992, cat:"Grote Ronde", renner:"Miguel Induráin", nat:"🇪🇸 Spanje", race:"Tour de France + Giro d'Italia", kort:"Een renner wint voor het eerst in jaren zowel de Ronde van Italië als de Ronde van Frankrijk in hetzelfde seizoen", lang:"Induráin voltooide dat jaar de zeldzame Giro-Tour dubbel, een prestatie die door slechts enkele renners in de moderne wielergeschiedenis is bereikt. Hij won zowel de Giro d'Italia als de Tour de France in hetzelfde jaar, wat zijn fenomenale vorm en onvermoeibare willskracht aantoonde. Dit was pas het tweede jaar dat hij beide monumentale koersen won en bewees dat zijn eerste Tour-zege geen toevalstreffer was. De dubbel werd beschouwd als de kroon op de wielerloopbaan van die tijd.", diff:2 },

  "HC003": { jaar:1993, cat:"Grote Ronde", renner:"Miguel Induráin", nat:"🇪🇸 Spanje", race:"Tour de France + Giro d'Italia", kort:"Voor het tweede jaar op rij lukt het een renner om zowel Italië als Frankrijk te veroveren", lang:"Induráin herhaalde dat jaar zijn Giro-Tour dubbel en schreef daarmee wielergeschiedenis. Voor het tweede opeenvolgende jaar won hij beide grootste rondes in dezelfde seizoen, een unieke prestatie in het moderne wielrennen. Dit zou tot zijn tijd toe alleen Merckx voor hem hebben gedaan, wat Induráin in de boeken van de wielsport plaatste als een van de meest dominante renners ooit. Zijn consistentie en mentale sterkte waren ongekend op deze niveaus van professionele competitie.", diff:3 },

  "HC004": { jaar:1995, cat:"Grote Ronde", renner:"Miguel Induráin", nat:"🇪🇸 Spanje", race:"Tour de France", kort:"Een renner schrijft wielrengeschiedenis met zijn vijfde opeenvolgende overwinning in de grootste rittenkoers ter wereld", lang:"Miguel Induráin won dat jaar zijn vijfde Tour de France op rij, een record dat tot dan toe nooit vertoond was in het moderne wielrennen en nog steeds gedeeld staat met Eddy Merckx. Dit monumentale aantal overwinningen opeenvolgend toonde zijn absolute dominantie in de Ronde van Frankrijk aan. Met geraffelde tijdritprestaties en sterke bergbeklimmingen deed hij wat velen onmogelijk achtten: vijf jaar op rij het geel behouden. Deze prestatie zal altijd herinnerd worden als een van de meest ijzingwekkende records in de wielergeschiedenis.", diff:1 },

  "HC005": { jaar:1996, cat:"Grote Ronde", renner:"Bjarne Riis", nat:"🇩🇰 Denemarken", race:"Tour de France", kort:"Een Deen verrast de wielerwereld en zet de beste klimmers op de Mont Ventoux volledig in de wind", lang:"Bjarne Riis won de Tour de France in een sensationele prestatie die de wielerwereld volledig verraste. Met zijn vermogen op de Mont Ventoux nam hij een decisieve voorsprong op zijn concurrenten en controleerde die tot Parijs. Jaren later gaf Riis toe dat hij de koers had gewonnen met behulp van EPO en andere dopingmiddelen. Ondanks latere doping-schandalen blijft een van de controversiële jaren in de Tourgeschiedenis, waarbij het gele trui achteraf veel van zijn glans verloor.", diff:2 },

  "HC006": { jaar:1997, cat:"Grote Ronde", renner:"Jan Ullrich", nat:"🇩🇪 Duitsland", race:"Tour de France", kort:"Een 23-jarige Duitser wordt de jongste Tourwinnaar in decennia en rijdt de tijdrit van zijn leven", lang:"Jan Ullrich won dat jaar op 23-jarige leeftijd de Tour de France en werd daarmee de jongste winnaar in decennia. Met fenomenale prestaties in de bergen en vooral een magistrale tijdrit op het einde van de koers, overtuigde hij volledige peloton van zijn talent. Als opvolger van Riis leek Ullrich voorbestemd voor een glorieuze en langdurige carrière van Touroverwinningen. Zijn aggressive rijstijl en mentale veerkracht gaven hoop op jarenlange dominantie, hoewel dit later niet geheel volgens plan zou verlopen.", diff:2 },

  "HC007": { jaar:1998, cat:"Grote Ronde", renner:"Marco Pantani", nat:"🇮🇹 Italië", race:"Tour de France + Giro d'Italia", kort:"Een flamboyante Italiaan met zijn kenmerkende bandana klimt als een engel en verovert twee grote rondes in één zomer", lang:"Marco Pantani voltooide dat jaar de legendarische Giro-Tour dubbel met zijn karakteristieke elan en elegante klimbewegingen. Zijn aanval op Alpe d'Huez hoort zonder twijfel tot de mooiste momenten in de wielerhistorie ooit vastgelegd. Met zijn roze bandana en flamboyante stijl won hij beide monumentale koersen in dezelfde zomer, wat hem een nationale held maakte in Italië. Pantani's talent en passie zouden helaas later in de schaduw komen te staan door de tragische dopingaffaire dat jaar.", diff:2 },

  "HC008": { jaar:2006, cat:"Grote Ronde", renner:"Óscar Pereiro", nat:"🇪🇸 Spanje", race:"Tour de France", kort:"Na een diskwalificatie weken na de finish wordt een verrassende winnaar alsnog in de geschiedenisboeken geschreven", lang:"Óscar Pereiro werd de officiële Tourwinnaar van dat jaar nadat Floyd Landis positief had getest op verboden anabolen stereoïden en zijn titel werd ingetrokken. Hoewel Pereiro een sterke coureur was, was hij niet de verwachte winnaar van deze editie. Het schandaal rond Landis zorgde voor veel controverse en steide de integriteit van het wielrennen ter discussie. Pereiro's naam zou voor altijd verbonden blijven met deze bijzondere omstandigheden van een Tourtitel.", diff:3 },

  "HC009": { jaar:2007, cat:"Grote Ronde", renner:"Alberto Contador", nat:"🇪🇸 Spanje", race:"Tour de France", kort:"Een explosieve Spanjaard verslaat een Duitser in de bergen en zet zijn eerste grote stempel op het wielrennen", lang:"Alberto Contador won dat jaar zijn eerste Tour de France op dramatische wijze, met explosieve aanvallen in de bergen die zijn concurrenten volledig vernietigden. Voor Cadel Evans en Levi Leipheimer finishte hij, wat zijn dominantie in dat seizoen onderstreepte. Met zijn scherpe tactische inzicht en vermogen om aan te vallen op de meest onverwachte momenten, legde Contador zijn eerste grote stempel op het wielrennen. Deze overwinning markeerde het begin van een generatie waarin Contador een centrale speler zou worden in de Tourfights.", diff:2 },

  "HC010": { jaar:2008, cat:"Grote Ronde", renner:"Carlos Sastre", nat:"🇪🇸 Spanje", race:"Tour de France", kort:"Een stille werker maakt het verschil op Alpe d'Huez en pakt de gele trui in de slotweek", lang:"Carlos Sastre won de Tour de France na een magistrale aanval op de legendarische Alpe d'Huez in het derde-na-laatste stadion. Met een perfecte timing en mentale sterkte overwon hij zijn rivalen op het meest cruciale moment en pakte de gele trui in de slotweek. Sastre was niet de verwachte winnaar van tevoren, maar door zijn doortastendheid en geesteskracht schreef hij een van de mooiste wielerhistorische verhalen. Zijn broer-in-law Frank Schleck finishte tweede en ondersteunde hem perfect tot het einde.", diff:3 },

  "HC011": { jaar:2010, cat:"Grote Ronde", renner:"Andy Schleck", nat:"🇱🇺 Luxemburg", race:"Tour de France", kort:"Een Luxemburger wordt Tourwinnaar na de diskwalificatie van zijn rivaal wegens een verboden stof in een biefstuk", lang:"Andy Schleck werd officieel winnaar van de Tour nadat Alberto Contador werd gediskwalificeerd vanwege het verbodene anabolensteroïde clenbuterol dat in zijn bloed werd aangetroffen na een test tijdens de Ronde. Hoewel dit Schleck de gele trui gaf, was het een controversiële uitkomst die veel discussie veroorzaakte in de wielersport. Contador stelde dat het van een vervuilde biefstuk afkomstig was, maar de UCI negeerde zijn verdediging en gaf de titel aan Schleck. Dit was voor Schleck een bitterzoete overwinning die altijd deze twijfel zou meebrengen.", diff:3 },

  "HC012": { jaar:2011, cat:"Grote Ronde", renner:"Cadel Evans", nat:"🇦🇺 Australië", race:"Tour de France", kort:"De eerste Australiër ooit wint de Tour de France na jaren van bijna-misses", lang:"Cadel Evans werd dat jaar de eerste Australische Tourwinnaar, waarmee hij een droom van het hele Australische wielrennen vervulde. Na jaren van sterke prestaties waarbij hij telkens net niet aan het podium kwam, greep hij eindelijk zijn moment en versloeg de Schleck-broers op cruciale momenten in de bergritten. Zijn tactische spel en mentale veerkracht waren impeccabel in deze editie, vooral op de slottijdrit waar hij de leiding definitief innam. Voor Australië was dit een historisch moment dat het land op wielrenkaart zette en inspiratie gaf aan toekomstige generaties.", diff:2 },

  "HC013": { jaar:2012, cat:"Grote Ronde", renner:"Bradley Wiggins", nat:"🇬🇧 Groot-Brittannië", race:"Tour de France", kort:"De eerste Brit ooit wint de Tour de France — een historisch moment voor het Britse wielrennen", lang:"Bradley Wiggins schreef geschiedenis als de eerste Britse Tourwinnaar, waarmee hij een ongelooflijk moment creëerde voor heel Groot-Brittannië en het Britse wielrennen. Met zijn lichte gewicht, sterke mentale voorbereiding en meesterlijke teamtactiek onder leiding van Sky won hij de koers overtuigend. Later zou hij ook olympisch kampioen worden op de tijdrit, wat zijn jaar compleet maakte. Wiggins' overwinning betekende een enorme boost voor het wielrennen in Groot-Brittannië en opende deuren voor vele talentvolle Britse renners daarna.", diff:1 },

  "HC014": { jaar:2013, cat:"Grote Ronde", renner:"Chris Froome", nat:"🇬🇧 Groot-Brittannië", race:"Tour de France", kort:"Een Brit wint voor het tweede jaar op rij de Tour de France voor zijn team", lang:"Chris Froome won dat jaar zijn eerste Tour de France voor Team Sky, met onder andere een memorabele aanval op de Mont Ventoux waar hij met slechts een fles water in zijn hand bergop fietste. Zijn mentale concentratie en lichamelijke voorbereiding waren perfectie, en hij overtuigde volledige wielerwereld van zijn vermogen om meerdere Tours te winnen. Met twee Britten op het podium vervierdubbelde Froome het succes van Team Sky in Frankrijk. Deze overwinning zou het begin zijn van een dominantie door Froome die decennium zou bepalen.", diff:1 },

  "HC015": { jaar:2014, cat:"Grote Ronde", renner:"Vincenzo Nibali", nat:"🇮🇹 Italië", race:"Tour de France", kort:"Een Italiaan domineert een Tour die in de war wordt gestuurd door valpartijen en meerdere favorieten verliest", lang:"Vincenzo Nibali won de Tour op indrukwekkende wijze en domineerde de koers volledig ondanks dat Froome, Contador en Cavendish allemaal vitaal uitvielen door valpartijen. De Italiaan toonde zijn veelzijdigheid met sterke prestaties in de bergen en de tijdrit, wat bewees dat hij een volledige klassieker was. Met zijn tactische inzicht en agressieve rijstijl controleerde Nibali de koers van begin tot eind. Zijn overwinning werd gezien als een van de meest overtuigende performances in jaren, ondanks de afwezigheid van enkele topfavorieten.", diff:2 },

  "HC016": { jaar:2015, cat:"Grote Ronde", renner:"Chris Froome", nat:"🇬🇧 Groot-Brittannië", race:"Tour de France", kort:"Een klimmer herhaalt zijn succes en wint opnieuw de grootste rittenkoers ter wereld", lang:"Chris Froome won dat jaar zijn tweede Tour de France, waarbij zijn aanval op La Pierre-Saint-Martin in de zware regen beeldbepalend was. Met zijn fenomenale voorbereiding en mentale veerkracht overwon hij zijn rivalen op de meest cruciale momenten. Froome's vermogen om onder druk te presteren was opmerkelijk, en hij toonde aan dat hij niet alleen een eenmalige winnaar was maar een ware campagneleider. Deze tweede titel positioneerde hem als een van de meest succesvolle renners van zijn generatie.", diff:2 },

  "HC017": { jaar:2016, cat:"Grote Ronde", renner:"Chris Froome", nat:"🇬🇧 Groot-Brittannië", race:"Tour de France", kort:"Een renner bevestigt zijn status als tourwinnaar van zijn generatie met zijn derde grote zege", lang:"Chris Froome pakte zijn derde Tour de France dat jaar, ondanks hevige oppositie van Nairo Quintana en andere toprenners. Met zijn karakteristieke stijl van constant tempo maken in de bergen, wisselde hij zijn concurrenten af en controleerde de koers vanuit een dominante positie. Froome's drie Tour-titels in vier jaar zette hem in een zeer exclusief gezelschap van grote wielrenners. Deze overwinning bevestigde definitief zijn status als tourwinnaar van zijn generatie en een van de meest complete wielrenners ooit.", diff:2 },

  "HC018": { jaar:2017, cat:"Grote Ronde", renner:"Chris Froome", nat:"🇬🇧 Groot-Brittannië", race:"Vuelta a España", kort:"De regerende Tourchampion verlegt zijn focus naar Spanje en voegt een tweede grote ronde toe aan zijn palmares", lang:"Chris Froome won dat jaar de Vuelta a España, zijn eerste Vuelta-titel en zijn vierde overwinning in een grote ronde wereldwijd. Door zijn aandacht naar Spanje te verschuiven nadat hij al jaren de Tour domineerde, toonde hij zijn vermogen om op verschillende niveaus te presteren. Met zijn methodische aanvallen en sterke controlering van de koers schreef hij opnieuw geschiedenis. Deze Vuelta-overwinning consolideerde Froomes reputatie als een van de meest complete wielrenners van de 21e eeuw, met overwinningen in alle drie de grote rondes.", diff:3 },

  "HC019": { jaar:2018, cat:"Grote Ronde", renner:"Geraint Thomas", nat:"🇬🇧 Groot-Brittannië", race:"Tour de France", kort:"Een ploegmaat van de regerende kampioen verrast iedereen en pakt de gele trui voor zijn teamleider", lang:"Geraint Thomas versloeg zijn eigen ploegmaat Chris Froome en won dat jaar verrassend de Tour de France, wat veel observatoren schokten. Met een perfecte mentaliteit en teamtactische steun van Team Sky, manipuleerde Thomas de koers op sleutelmomenten. Zijn aanval op Alpe d'Huez was decisief, en hij bouwde voort op zijn voordeel naar Parijs. Dit was een dramatische verandering van scenario's waar Thomas, lang gezien als een ploegmaat, zich plotseling als hoofdkandidaat ontpopte en de Tour van onder zijn ploegmaat won.", diff:2 },

  "HC020": { jaar:2019, cat:"Grote Ronde", renner:"Egan Bernal", nat:"🇨🇴 Colombia", race:"Tour de France", kort:"Een jonge Colombiaan verslaat ervaren concurrenten en wordt de jongste Tourwinnaar van de 21e eeuw", lang:"Egan Bernal won dat jaar de Tour de France op slechts 22-jarige leeftijd, waardoor hij de jongste Tourwinnaar van de 21e eeuw werd. Met zijn explosieve aanvallen en jeugdige fris en mentale sterkte overwon hij ervaren concurrenten als Geraint Thomas en Julian Alaphilippe. Bernal toonde aan dat de toekomst van het wielrennen in handen was van een nieuwe generatie van dynamische klimmertalenten. Zijn overwinning inspireerde jonge wielrenners over de hele wereld en plaatste Colombia op de wielerkaart met een Tourwinning op jonge leeftijd.", diff:2 },

  "HC021": { jaar:2020, cat:"Grote Ronde", renner:"Tadej Pogačar", nat:"🇸🇮 Slovenië", race:"Tour de France", kort:"Een jonge Sloveense renner voert een spektakulaire manoeuvre uit en verrast alle favorieten in de slottijdrit", lang:"Tadej Pogačar won dat jaar op 21-jarige leeftijd de Tour de France in een spectaculaire slottijdrit, waardoor hij Primož Roglič van de gele trui afhielp in het allerlaatste onderdeel. Met zijn kombinatie van bergkracht en tijdritvermogen toonde hij aan dat hij een volledige klasser was. Pogačar's prestatie was een van de meest verrassen in recente wielergeschiedenis, want hij veranderde het algemene klassement volledig in het allerlaatste moment. Deze overwinning markeerde de opkomst van een buitengewoon talent dat de volgende decennium zou domineren.", diff:1 },

  "HC022": { jaar:2021, cat:"Grote Ronde", renner:"Tadej Pogačar", nat:"🇸🇮 Slovenië", race:"Tour de France", kort:"Dezelfde renner herhaalt zijn succes en domineert het peloton met aanvallen op alle fronten", lang:"Tadej Pogačar herhaalde dat jaar zijn Toursucces en domineerde het peloton compleet met aanvallen op alle fronten. Met zijn explosieve vermogen in de bergen en zijn sterke tijdritprestaties controleerde hij de koers van begin tot einde. Pogačar toonde aan dat zijn -zege geen toevalstreffer was maar het begin van een lange periode van dominantie. Zijn twee opeenvolgende Tour-titels op jonge leeftijd plaatsten hem in een selecte groep van grote klassieken en bevestigde zijn status als de toekomstige generatie-leider in het wielrennen.", diff:2 },

  "HC023": { jaar:2021, cat:"Grote Ronde", renner:"Egan Bernal", nat:"🇨🇴 Colombia", race:"Giro d'Italia", kort:"Een Colombiaan wint de Italiaanse ronde en herbevestigt zijn status als topklimmer", lang:"Egan Bernal won dat jaar de Giro d'Italia, waarmee hij zijn eerste grote ronde-titel buiten de Tour de France verzekerde en zijn status als topklimmer herbevestigde. Met zijn aggressieve ritmen in de bergen en sterke mentale focus controleerde Bernal de Giro van begin tot eind. Dit was een belangrijke overwinning die aantoonde dat Bernal niet alleen een eenmalige Tourrinnaar was maar een complete classics. De Colombiaan bewees dat hij tegen de allerbeste kon winnen en dat zijn Toursucces van dat jaar geen toevalstreffer was geweest.", diff:2 },

  "HC024": { jaar:2022, cat:"Grote Ronde", renner:"Jonas Vingegaard", nat:"🇫🇷 Frankrijk", race:"Tour de France", kort:"Een Fransman verslaat de topfavoriet Pogačar en pakt zijn eerste grote ronde-titel", lang:"Jonas Vingegaard won dat jaar de Tour de France en versloeg sensationeel de topfavoriet Tadej Pogačar in een spectaculaire strijd in de bergen. Met zijn fenomenale bergprestaties vooral op Hautacam zorgde Vingegaard voor een van de meest dramatische einden in recente Tourchiedenis. Als Frans renner was dit een enorm moment voor Frankrijk, dat eindelijk een nieuwe Tourwinnaar voortbracht na jaren zonder nationale held. Vingegaard's mentale sterkte en lichamelijke voorbereiding waren perfectie, en hij toonde aan dat Pogačar verslagen kon worden.", diff:2 },

  "HC025": { jaar:2022, cat:"Grote Ronde", renner:"Remco Evenepoel", nat:"🇧🇪 België", race:"Vuelta a España", kort:"Een jong talent uit België wint zijn eerste grote ronde op spectaculaire wijze", lang:"Remco Evenepoel won dat jaar op 22-jarige leeftijd de Vuelta a España, waarmee hij zijn eerste grote ronde-titel verzekerde en zich als een stijgende ster in het wielrennen positioneerde. Met zijn combinatie van bergkracht en tactische inzicht controleerde Evenepoel de koers op cruciale momenten. De Belgische renner toonde aan dat hij niet alleen tijdrit- en één-daags-racegoeroe was, maar ook over het vermogen beschikt om grote rondes op jonge leeftijd te winnen. Dit was een monumentale overwinning die de toekomst van het Belgische wielrennen opende.", diff:3 },

  "HC026": { jaar:2023, cat:"Grote Ronde", renner:"Jonas Vingegaard", nat:"🇫🇷 Frankrijk", race:"Tour de France", kort:"Een Fransman herhaalt zijn succes en verstoet opnieuw Pogačar in een monumentale bergstrijd", lang:"Jonas Vingegaard herhaalde dat jaar zijn Toursucces en versloeg opnieuw Tadej Pogačar in een monumentale bergstrijd vol dramatische momenten. Met zijn uitzonderlijke bergprestaties vooral in de Pyreneeën zorgde Vingegaard voor een van de spannendste Tour-edities in jaren. Zijn twee opeenvolgende Tour-titels plaatsten hem in een exclusief gezelschap van grote wielrenners. Vingegaard bewees dat zijn -zege geen toevalstreffer was en dat hij werkelijk een complete klasser was die de Tour op zijn niveau kon domineren. Dit was het hoogtepunt van zijn carrière tot dusverre.", diff:3 },

  "HC027": { jaar:2023, cat:"Grote Ronde", renner:"Sepp Kuss", nat:"🇺🇸 Verenigde Staten", race:"Vuelta a España", kort:"Een Amerikaanse renner wint voor het eerst ooit de Vuelta en zet Amerika op de kaart", lang:"Sepp Kuss won dat jaar de Vuelta a España en werd daarmee de eerste Amerikaanse renner ooit die deze grote ronde won. Met zijn consistente bergprestaties en mentale focus controleerde Kuss de koers gedurende drie weken. Voor Amerika was dit een historisch moment dat lange tijd werd gewacht - de Vuelta was de enige grote ronde zonder Amerikaanse winnaar. Kuss' overwinning inspireerde toekomstige generaties Amerikaanse wielrenners en toonde aan dat ook minder verwachte kandidaten deze monumentale koersen konden winnen.", diff:3 },

  "HC028": { jaar:2024, cat:"Grote Ronde", renner:"Tadej Pogačar", nat:"🇸🇮 Slovenië", race:"Tour de France", kort:"Een Sloveense renner wint spectaculair en domineert het moderne wielrennen", lang:"Tadej Pogačar won dat jaar zijn derde Tour de France in een spectaculaire performance die het wielrennen schudde. Met explosieve aanvallen in de bergen en dominante tijdritten controleerde hij de koers volledig. Pogačar's derde Tourtitel op jonge leeftijd plaatste hem onder de all-time greats van het wielrennen. Zijn vermogen om op alle terrein te excelleren - bergen, tijdrit, taktische inzicht - maakte hem de meest volledige renner van zijn generatie en misschien wel van alle tijden.", diff:1 },

  "HC029": { jaar:2024, cat:"Grote Ronde", renner:"Tadej Pogačar", nat:"🇸🇮 Slovenië", race:"Giro d'Italia", kort:"Dezelfde renner voert een Giro-Tour dubbel uit en schrijft de wielergeschiedenis", lang:"Tadej Pogačar schreef dat jaar wielergeschiedenis door de Giro-Tour dubbel uit te voeren en beide grootste rondes in hetzelfde seizoen te winnen. Dit was een monumentale prestatie die weinig renners hebben kunnen bereiken in het moderne wielrennen. Met zijn dominante performances in beide koersen toonde Pogačar aan dat hij een volledige klassieker was voor de eeuwen. De dubbel plaatste hem permanent in de wielerhistorie als een van de meest uitstekende atleten ooit in dit sport.", diff:1 },

  "HC030": { jaar:1993, cat:"Klassiek", renner:"Johan Museeuw", nat:"🇧🇪 België", race:"Ronde van Vlaanderen", kort:"Een Belgisch kampioen domineert in de modder en wind van de Vlaamse kasseien", lang:"Johan Museeuw won de Ronde van Vlaanderen dat jaar en bevestigde zijn status als de heersende kampioen op de Vlaamse kasseien. Met zijn kracht, tactische inzicht en vermogen om in zware omstandigheden te rijden, domineerde Museeuw de koers. Zijn overwinning op het vogelwijs parcours van de Ronde was een showcase van zijn klassieke talent. Deze zege was het begin van Museeuw's dominantie in de voorjaarsklassieken en maakte hem tot een van de belangrijkste renners van zijn generatie.", diff:2 },

  "HC031": { jaar:1995, cat:"Klassiek", renner:"Johan Museeuw", nat:"🇧🇪 België", race:"Parijs-Roubaix", kort:"Een koereur rijdt solo naar het finish en voelt zich in zijn element op de hellingen", lang:"Johan Museeuw won Parijs-Roubaix dat jaar, een van de meest prestigieuze klassieke ritten. Met zijn sterke voeten en aanpassingsvermogen aan de zware kasseien controleerde Museeuw de koers op zijn eigen termen. Hij bewees waarom hij de specialist was van de moeilijkste Vlaamse en Noordfranse routes. Zijn solo-aanval van verre en zijn overtuigende eindsprint toonden waarom Museeuw de beste klassieke rijder van zijn tijd was.", diff:2 },

  "HC032": { jaar:2000, cat:"Klassiek", renner:"Johan Museeuw", nat:"🇧🇪 België", race:"Parijs-Roubaix", kort:"Een veteraan van het klassieke wielrennen herhaalt zijn glorie op de Molenberg", lang:"Johan Museeuw won Parijs-Roubaix opnieuw dat jaar, op latere leeftijd, wat aantoonde dat zijn klassieke vermogen niet verdween met leeftijd. Met zijn karakteristieke stijl van aanvallen op de Molenberg zorgde Museeuw voor een van de mooiste momenten in zijn lange carrière. Deze overwinning toonde aan dat Museeuw niet alleen vroeg in zijn carrière dominant was, maar dat hij de mentale focus en kracht behield om tegen de besten te winnen. Zijn derde Roubaix-zege solidifieerde zijn plaats als één van de allerbeste klassieke rijders ooit.", diff:3 },

  "HC033": { jaar:2002, cat:"Klassiek", renner:"Johan Museeuw", nat:"🇧🇪 België", race:"Parijs-Roubaix", kort:"Een Belgisch icoon wint voor het derde keer en sluit zijn carrière af met glorie", lang:"Johan Museeuw won dat jaar zijn derde Parijs-Roubaix-titel en sloot zijn lange en glorieuze carrière af met deze monumentale zege. Op 36-jarige leeftijd toonde Museeuw dat hij nog steeds de klassieke kasseien beter kon rijden dan enig ander. Zijn derde Roubaix-zege was een fitting einde op een carrière vol monumentale prestaties. Museeuw's drie Roubaix-titels bleven een record tot zijn pensionering en definieerden hem als een van de allerbeste klassieke renners in de geschiedenis.", diff:3 },

  "HC034": { jaar:2005, cat:"Klassiek", renner:"Tom Boonen", nat:"🇧🇪 België", race:"Parijs-Roubaix", kort:"Een jonge Belgische renner verovert de Hel van het Noorden en schakelt Museeuw uit", lang:"Tom Boonen won dat jaar Parijs-Roubaix op spectaculaire wijze, waarmee hij de erfenis van Johan Museeuw als heersende Roubaix-kampioen overnam. Met zijn sterke voeten en explosieve vermogen in de kasseien domineerde Boonen de koers en liet geen twijfel over wie de sterkste was. Dit was het begin van Boonen's dominantie in de klassieke rennen en plaatste hem als de opvolger van Museeuw. Zijn zege betekende een overgang naar een nieuwe generatie van klassieke renners die België zou blijven domineren.", diff:2 },

  "HC035": { jaar:2006, cat:"Klassiek", renner:"Tom Boonen", nat:"🇧🇪 België", race:"Parijs-Roubaix", kort:"Dezelfde renner herhaalt zijn succes en bevestigt zijn overheersing in de klassieken", lang:"Tom Boonen herhaalde dat jaar zijn Roubaix-succes en bevestigde volledig zijn overheersing in de klassieke rennen. Met zijn karakteristieke aanvallen in de Carrefour de l'Arbre controleerde Boonen de koers op zijn eigen termen. Deze tweede opeenvolgende Roubaix-titel toonde aan dat Boonen niet alleen een eenmalige kampioen was maar een compleet klassieke specialist. Zijn dominantie dat jaar- plaatste hem als één van de beste klassieke renners van zijn generatie.", diff:2 },

  "HC036": { jaar:2008, cat:"Klassiek", renner:"Tom Boonen", nat:"🇧🇪 België", race:"Parijs-Roubaix", kort:"Een Belgisch kampioen schrijft geschiedenis met zijn derde Roubaix-zege", lang:"Tom Boonen won dat jaar zijn derde Parijs-Roubaix-titel, waarmee hij zich plaatste in de selecte groep van renners die dit monument meerdere malen hebben gewonnen. Met zijn fenomenale voeten op de kasseien en mentale focus controleerde Boonen opnieuw de koers naar zijn wil. Deze derde Roubaix-zege solidiifieerde zijn plaats als één van de allerbeste klassieke renners van alle tijden. Boonen's drie Roubaix-titels in vier jaar toonden zijn absolute dominantie in de voorjaarsklassieken.", diff:2 },

  "HC037": { jaar:2009, cat:"Klassiek", renner:"Tom Boonen", nat:"🇧🇪 België", race:"Parijs-Roubaix", kort:"Een Belgische legend voegt zijn vierde zege toe en evenaaart Museeuw", lang:"Tom Boonen won dat jaar zijn vierde Parijs-Roubaix-titel, waarmee hij Johan Museeuw in het aantal Roubaix-zeges evenaaarde. Met zijn karakteristieke aanvallen en ongeëvenaarde vermogen op de kasseien schrijft Boonen zijn naam permanent in de wielergeschiedenis. Deze vierde zege plaatste hem echt als één van de allergrootsten in de klassieke wielrennen. Boonen's dominantie in Parijs-Roubaix was ongekend en maakte hem tot het gezicht van het klassieke wielrennen voor een hele generatie.", diff:2 },

  "HC038": { jaar:2010, cat:"Klassiek", renner:"Fabian Cancellara", nat:"🇨🇭 Zwitserland", race:"Ronde van Vlaanderen + Parijs-Roubaix", kort:"Een Zwitser wint in hetzelfde seizoen zowel de Ronde van Vlaanderen als Parijs-Roubaix", lang:"Fabian Cancellara schreef dat jaar klassieke wielergeschiedenis door in hetzelfde seizoen zowel de Ronde van Vlaanderen als Parijs-Roubaix te winnen. Dit was een monumentale dubbel die zeer weinig renners hebben kunnen bereiken. Met zijn titanische kracht en volledige klassieke veelzijdigheid domineerde Cancellara beide monumenten. Deze dubbel plaatste hem direct onder de allerbeste klassieke renners van alle tijden en toonde zijn absolute dominantie in de voorjaarsklassieken.", diff:2 },

  "HC039": { jaar:2011, cat:"Klassiek", renner:"Philippe Gilbert", nat:"🇧🇪 België", race:"Classics sweep (RVV + Roubaix + Walonnen)", kort:"Een Belgische renner voert een ongekende sweep van de voorjaarsklassieken uit", lang:"Philippe Gilbert schreef dat jaar een ongelooflijk hoofdstuk in de klassieke wielrengeschiedenis door alle grote voorjaarsklasseken op rij te winnen - Ronde van Vlaanderen, Parijs-Roubaix én Walonnen Pijlen. Dit 'Classics sweep' is zeer zeldzaam en plaatste Gilbert direct onder de allergrootsten. Met zijn explosieve vermogen en mentale concentratie domineerde Gilbert alle klassieke terreinen. Deze zegereeks was het hoogtepunt van Gilberts carrière en maakte hem tot een icoon van het klassieke wielrennen.", diff:3 },

  "HC040": { jaar:2012, cat:"Klassiek", renner:"Tom Boonen", nat:"🇧🇪 België", race:"Parijs-Roubaix", kort:"De Belgische legend voegt zijn vijfde zege toe aan een ongeëvenaard palmares", lang:"Tom Boonen won dat jaar zijn vijfde Parijs-Roubaix-titel en schreef daarmee wielergeschiedenis met meer Roubaix-zeges dan enig ander renner ooit. Met zijn karakteristieke voeten op kasseien en ongelofelijke mentale sterkte domineerde Boonen opnieuw de Hel van het Noorden. Deze vijfde Roubaix-zege was de kroon op Boonen's phenomenale carrière in de klasseken. Zijn dominantie was ongekend en maakte hem tot de allergrootste Parijs-Roubaix-specialist ooit.", diff:2 },

  "HC041": { jaar:2013, cat:"Klassiek", renner:"Fabian Cancellara", nat:"🇨🇭 Zwitserland", race:"Ronde van Vlaanderen", kort:"Een Zwitserse kampioen domineert en zet zijn stempel op de Vlaamse kasseien", lang:"Fabian Cancellara won dat jaar de Ronde van Vlaanderen en domineerde voledig op de Vlaamse kasseien met zijn karakteristieke titanische kracht. Met zijn aanvallen op Molenberg zorgde Cancellara voor één van de meest spectaculaire performances in recente RVV-geschiedenis. Deze zege bevestigde Cancellara's status als één van de allerbeste klassieke renners van zijn generatie. Zijn vermogen om Berg na Berg aan te vallen en zijn concurrenten af te schudden toonde waarom hij een allround klassieke champion was.", diff:2 },

  "HC042": { jaar:2014, cat:"Klassiek", renner:"Fabian Cancellara", nat:"🇨🇭 Zwitserland", race:"Parijs-Roubaix", kort:"Een Zwitserse classicist voegt Roubaix toe aan zijn monumentale palmares", lang:"Fabian Cancellara won dat jaar Parijs-Roubaix en voegde dit monument toe aan zijn al indrukwekkende palmares van klassieke zeges. Met zijn fenomenale voeten en mentale toughness domineerde Cancellara de Hel van het Noorden. Dit was een fitting moment in zijn glorieuze carrière waarin hij aantoonde dat hij een echte allround klassieke champion was. Cancellara's palmares van grote klasseken maakte hem tot één van de allergrootsten in de klassieke wielrengeschiedenis.", diff:2 },

  "HC043": { jaar:2019, cat:"Klassiek", renner:"Wout van Aert", nat:"🇧🇪 België", race:"Amstel Gold Race", kort:"Een jong talent domineert en wint zijn eerste groot klassieke monument", lang:"Wout van Aert won dat jaar de Amstel Gold Race en behaalde zijn eerste monumentale zege in de klassieke wielrennen. Met zijn explosieve vermogen en sterkheid in heuvelachtig terrein domineerde van Aert de koers. Dit was het begin van van Aert's dominantie in de klasseken en plaatste hem als de toekomst van het klassieke wielrennen. Zijn zege inspireerde toekomstige generaties en toonde dat jonge talenten tegen de traditie in konden winnen.", diff:2 },

  "HC044": { jaar:2020, cat:"Klassiek", renner:"Wout van Aert", nat:"🇧🇪 België", race:"Milaan-San Remo", kort:"Een allround kampioen domineert de langste klassieke rit en zet een nieuw record", lang:"Wout van Aert won dat jaar Milaan-San Remo en domineerde deze langste klassieke rit met zijn explosieve vermogen. Dit was een monumentale overwinning voor van Aert die aantoonde dat hij niet alleen op hellingen maar ook op de weg dominant kon zijn. Zijn zege op één van de oudste klasseken in het wielrennen toonde zijn veelzijdigheid en mentale sterkte. Van Aert's prestatie plaatste hem als een true all-rounder in het klassieke wielrennen.", diff:3 },

  "HC045": { jaar:2021, cat:"Klassiek", renner:"Wout van Aert", nat:"🇧🇪 België", race:"Ronde van Vlaanderen", kort:"Een multi-talent domineert de Vlaamse kasseien en voegt RVV toe aan zijn palmares", lang:"Wout van Aert won dat jaar de Ronde van Vlaanderen en voegde dit klassieke monument toe aan zijn groeiend palmares. Met zijn sterkte en vermogen op kasseien domineerde van Aert de Vlaamse parcours geheel. Dit was aantoonden dat van Aert niet alleen een eenmalige klassieke winnaar was maar een echte champion op alle terrein. Zijn drie monumentale zeges in drie jaar plaatsten hem als één van de meest volledige klassieke renners van zijn generatie.", diff:2 },

  "HC046": { jaar:2021, cat:"Klassiek", renner:"Sonny Colbrelli", nat:"🇮🇹 Italië", race:"Parijs-Roubaix", kort:"Een Italiaan wint spektakulair op de kasseien van het Noorden", lang:"Sonny Colbrelli won dat jaar Parijs-Roubaix in een spektakulaire performance op de kasseien van het Noorden. Met zijn fenomenale voeten en mentale toughness domineerde Colbrelli de Hel van het Noorden. Deze overwinning was het hoogtepunt van Colbrelli's carrière tot dusverre en plaatste hem permanent onder de winnaars van dit prestigieuze monument. Zijn zege toonde aan dat ook onverwachte kandidaten deze koers kunnen domineren.", diff:3 },

  "HC047": { jaar:2022, cat:"Klassiek", renner:"Mathieu van der Poel", nat:"🇳🇱 Nederland", race:"Parijs-Roubaix", kort:"Een Nederlands talent domineert en pakt zijn eerste Roubaix", lang:"Mathieu van der Poel won dat jaar Parijs-Roubaix en behaalde zijn eerste zege op dit prestigieuze monument. Met zijn explosieve vermogen en volledig klassieke talent domineerde van der Poel de kasseien. Dit was een monumentale overwinning voor van der Poel die aantoonde dat hij werkelijk in dezelfde categorie speelde als de allergrootsten. Zijn zege inspireerde hoop in Nederland dat het klassieke wielrennen nog groot zou zijn.", diff:2 },

  "HC048": { jaar:2023, cat:"Klassiek", renner:"Mathieu van der Poel", nat:"🇳🇱 Nederland", race:"Parijs-Roubaix", kort:"Dezelfde renner herhaalt zijn succes en bevestigt zijn klassieke dominantie", lang:"Mathieu van der Poel herhaalde dat jaar zijn Roubaix-succes en bevestigde volledig zijn klassieke dominantie. Met zijn karakteristieke aanvallen domineerde van der Poel opnieuw de kasseien van het Noorden. Deze tweede opeenvolgende Roubaix-titel toonde dat van der Poel niet alleen een eenmalige kampioen was maar een echte klassieke specialist. Zijn twee Roubaix-titels plaatsten hem onder de meest respecteerde klassieke renners van zijn generatie.", diff:2 },

  "HC049": { jaar:2024, cat:"Klassiek", renner:"Mathieu van der Poel", nat:"🇳🇱 Nederland", race:"Parijs-Roubaix", kort:"Een Nederlands icoon voegt zijn derde Roubaix toe aan een monumentaal palmares", lang:"Mathieu van der Poel won dat jaar zijn derde Parijs-Roubaix-titel en schreef daarmee wielergeschiedenis als een van de meest dominante Roubaix-specialisten ooit. Met zijn fenomenale voeten op kasseien en mentale sterkte domineerde van der Poel opnieuw de Hel van het Noorden. Deze derde zege plaatste hem permanent onder de allergrootsten in de klassieke wielrengeschiedenis. Van der Poel's drie Roubaix-titels in drie jaar toonden zijn absolute en ongekende dominantie.", diff:1 },

  "HC050": { jaar:2019, cat:"Klassiek", renner:"Albano Bettiol", nat:"🇮🇹 Italië", race:"Ronde van Vlaanderen", kort:"Een Italiaan domineert en wint spektakulair op de Molenberg", lang:"Albano Bettiol won dat jaar de Ronde van Vlaanderen in een spektakulaire performance, met een kilométer-lange aanval op de Molenberg die zijn concurrenten vernietigde. Met zijn explosieve vermogen en mentale toughness domineerde Bettiol de Vlaamse kasseien. Deze zege was het hoogtepunt van Bettiol's carrière tot dusverre en plaatste hem permanent onder de winnaars van dit prestigieuze monument. Zijn prestatie toonde dat ook minder verwachte kandidaten deze klasseken kunnen domineren.", diff:2 },

  "HC051": { jaar:1993, cat:"Wereldkampioenschap", renner:"Lance Armstrong", nat:"🇺🇸 Verenigde Staten", race:"Wereldkampionschap Weg", kort:"Een jonge Amerikaan wordt wereldkampioen en zet zijn eerste stempel op het wielrennen", lang:"Lance Armstrong won dat jaar het Wereldkampioenschap Weg op zeer jonge leeftijd en schreef onmiddellijk wielergeschiedenis. Met zijn explosieve vermogen en jeugdige fris domineerde Armstrong het parcours. Dit was het begin van zijn veel geprezen carrière die helaas later zou worden overschaduwd door dopingschandalen. Op het moment voelde dit als het begin van een glorieuze toekomst vol monumentale prestaties, maar de geschiedenisse zou anders uitpakken.", diff:2 },

  "HC052": { jaar:1996, cat:"Wereldkampioenschap", renner:"Johan Museeuw", nat:"🇧🇪 België", race:"Wereldkampionschap Weg", kort:"Een Belgisch talent domineert en pakt de regenboogtrui", lang:"Johan Museeuw won dat jaar het Wereldkampioenschap Weg en behaalde de voornaamste titel in het wielrennen - de regenboogtrui. Met zijn klassieke vermogen en mentale sterkte domineerde Museeuw het WK-parcours. Dit was een fitting moment in Museeuw's carrière waarin hij zijn status als een van de meest complete renners bevestigde. De regenboogtrui plaatste hem permanent onder de allergrootsten van het wielrennen.", diff:2 },

  "HC053": { jaar:2005, cat:"Wereldkampioenschap", renner:"Tom Boonen", nat:"🇧🇪 België", race:"Wereldkampionschap Weg", kort:"Een Belgische young gun wint het Wereldkampioenschap en zet het wielrennen in vuur en vlam", lang:"Tom Boonen won dat jaar het Wereldkampioenschap Weg op jonge leeftijd en haalde de eerste en meeste geprezen titel in het wielrennen. Met zijn explosieve vermogen en mentale toughness domineerde Boonen het WK-parcours. Dit was het moment dat Boonen zich permanent als een sterke contender voor alle grote wedstrijden positioneerde. De regenboogtrui was het begin van een lange periode waarin Boonen het wielrennen zou domineren.", diff:2 },

  "HC054": { jaar:2011, cat:"Wereldkampioenschap", renner:"Mark Cavendish", nat:"🇬🇧 Groot-Brittannië", race:"Wereldkampionschap Weg", kort:"Een Brits sprinter sprint naar goud en pakt het Wereldkampioenschap", lang:"Mark Cavendish won dat jaar het Wereldkampioenschap Weg in een spektakulaire sprintfoto die het wielrennen in zijn greep hield. Met zijn fenomenale sprintkracht en timing domineerde Cavendish de massaspurt. Dit was één van de meest spannende WK-finishes in jaren en plaatste Cavendish permanent onder de allergrootsten van het wielrennen. De regenboogtrui bevestigde zijn status als één van de beste sprinters ooit.", diff:2 },

  "HC055": { jaar:2012, cat:"Wereldkampioenschap", renner:"Philippe Gilbert", nat:"🇧🇪 België", race:"Wereldkampionschap Weg", kort:"Een klassieke kampioen domineert en pakt zijn tweede grote titel van het jaar", lang:"Philippe Gilbert won dat jaar het Wereldkampioenschap Weg en voegde dit monument toe aan een jaar vol monumentale prestaties. Met zijn explosieve vermogen en mentale focus domineerde Gilbert het WK-parcours geheel. Dit was het hoogtepunt van Gilbert's fenomenale jaar vol zeges in de klasseken en grote wedstrijden. De regenboogtrui plaatste hem permanent als één van de compleetste renners van zijn generatie.", diff:2 },

  "HC056": { jaar:2015, cat:"Wereldkampioenschap", renner:"Peter Sagan", nat:"🇸🇰 Slowakije", race:"Wereldkampionschap Weg", kort:"Een veelzijdig talentje domineert en wint de regenboogtrui", lang:"Peter Sagan won dat jaar het Wereldkampioenschap Weg en behaalde de meest geprezen titel in het wielrennen - de regenboogtrui. Met zijn uitzonderlijke veelzijdigheid, mentale focus en klassieke vermogen domineerde Sagan het WK-parcours. Dit was het begin van Sagan's dominantie in het wielrennen en plaatste hem als de meest complete renner van zijn generatie. De regenboogtrui was fitting voor een renner van zijn kaliber en vermogen.", diff:2 },

  "HC057": { jaar:2016, cat:"Wereldkampioenschap", renner:"Peter Sagan", nat:"🇸🇰 Slowakije", race:"Wereldkampionschap Weg", kort:"Dezelfde renner herhaalt zijn succes en bevestigt zijn mondiale dominantie", lang:"Peter Sagan herhaalde dat jaar zijn Wereldkampioenschap-succes en bevestigde volledig zijn mondiale dominantie. Met zijn karakteristieke aanvallen en uitzonderlijke veelzijdigheid domineerde Sagan opnieuw het WK-parcours. Deze tweede opeenvolgende regenboogtrui plaatste hem onder de allergrootsten in het wielrennen en toonde zijn ongekende dominantie. Sagan's twee WK-titels bevestigden zijn status als één van de compleetste en meest talentvolle renners ooit.", diff:2 },

  "HC058": { jaar:2017, cat:"Wereldkampioenschap", renner:"Peter Sagan", nat:"🇸🇰 Slowakije", race:"Wereldkampionschap Weg", kort:"Een Slowaak voegt zijn derde titel toe en schrijft wielergeschiedenis", lang:"Peter Sagan won dat jaar zijn derde Wereldkampioenschap en schreef wielergeschiedenis als slechts de derde renner ooit met drie of meer WK-titels. Met zijn fenomenale vermogen, mentale sterkte en veelzijdigheid domineerde Sagan opnieuw het WK-parcours. Deze derde regenboogtrui plaatste hem permanent onder de allergrootsten in de wielrengeschiedenis. Sagan's drie WK-titels toonden zijn absolute dominantie en unieke positie in het wielrennen.", diff:2 },

  "HC059": { jaar:2020, cat:"Wereldkampioenschap", renner:"Julian Alaphilippe", nat:"🇫🇷 Frankrijk", race:"Wereldkampionschap Weg", kort:"Een Frans talent domineert en wint de regenboogtrui in een spectaculaire performance", lang:"Julian Alaphilippe won dat jaar het Wereldkampioenschap Weg in een spectaculaire performance die het wielrennen schudde. Met zijn explosieve aanvallen en mentale sterkte domineerde Alaphilippe het WK-parcours volledig. Dit was de kroon op zijn succesvolle seizoen vol monumentale prestaties. De regenboogtrui plaatste hem permanent onder de allergrootsten en toonde waarom hij één van de meest complete renners van zijn generatie was.", diff:2 },

  "HC060": { jaar:2021, cat:"Wereldkampioenschap", renner:"Julian Alaphilippe", nat:"🇫🇷 Frankrijk", race:"Wereldkampionschap Weg", kort:"Dezelfde Fransman herhaalt zijn succes en bevestigt zijn mondiale hegemonie", lang:"Julian Alaphilippe herhaalde dat jaar zijn Wereldkampioenschap-succes en bevestigde volledig zijn mondiale hegemonie. Met zijn karakteristieke aanvallen en uitzonderlijke mentale focus domineerde Alaphilippe opnieuw het WK-parcours. Deze tweede opeenvolgende regenboogtrui plaatste hem onder de allergrootsten en toonde zijn ongekende dominantie. Alaphilippe's twee WK-titels in twee jaar bevestigden zijn status als de meest dominante wegrenner van zijn tijd.", diff:2 },

  "HC061": { jaar:2022, cat:"Wereldkampioenschap", renner:"Remco Evenepoel", nat:"🇧🇪 België", race:"Wereldkampionschap Weg", kort:"Een jong talent domineert en wint de regenboogtrui op explosieve wijze", lang:"Remco Evenepoel won dat jaar het Wereldkampioenschap Weg op explosieve wijze en voegde deze monumentale titel toe aan zijn groeiend palmares. Met zijn titanische kracht, mentale focus en explosieve vermogen domineerde Evenepoel het WK-parcours. Dit was het begin van Evenepoel's potentiële WK-dominantie en plaatste hem als de toekomst van het wielrennen. De regenboogtrui was fitting voor een renner van zijn kaliber en voelde als het begin van een lange periode van dominantie.", diff:2 },

  "HC062": { jaar:2023, cat:"Wereldkampioenschap", renner:"Mathieu van der Poel", nat:"🇳🇱 Nederland", race:"Wereldkampionschap Weg", kort:"Een Nederlands allrounder domineert en pakt de regenboogtrui", lang:"Mathieu van der Poel won dat jaar het Wereldkampioenschap Weg en behaalde de meest geprezen titel in het wielrennen. Met zijn uitzonderlijke veelzijdigheid, klassieke vermogen en mentale sterkte domineerde van der Poel het WK-parcours. Dit was een fitting moment voor een renner van zijn kaliber die al veel monumentale prestaties had neergezet. De regenboogtrui plaatste hem permanent onder de allergrootsten en bevestigde zijn status als één van de compleetste renners van zijn generatie.", diff:2 },

  "HC063": { jaar:2024, cat:"Wereldkampioenschap", renner:"Tadej Pogačar", nat:"🇸🇮 Slovenië", race:"Wereldkampionschap Weg", kort:"Een Sloveense superster domineert en pakt de regenboogtrui als kroon op een fenomenaal jaar", lang:"Tadej Pogačar won dat jaar het Wereldkampioenschap Weg en voegde deze monumentale titel toe aan zijn reeds indrukwekkende palmares vol overwinningen. Met zijn titanische kracht, explosieve vermogen en mentale focus domineerde Pogačar het WK-parcours volledig. Dit was de kroon op een fenomenaal jaar waarin hij al twee Tours en een Giro won. De regenboogtrui plaatste hem permanent onder de allergrootsten en bevestigde zijn positie als de meest dominante renner van het hedendaagse wielrennen.", diff:1 },

  "HC064": { jaar:1995, cat:"Memorabel", renner:"Fabio Casartelli", nat:"🇮🇹 Italië", race:"Tour de France (Overlijden op Colle dell'Agnello)", kort:"Een Italiaanse renner verliest tragisch zijn leven op een bergpas tijdens de Tour", lang:"Fabio Casartelli overleed tragisch dat jaar tijdens de Tour de France toen hij van zijn fiets viel op de Colle dell'Agnello. Dit was een van de meest vreselijke momenten in de wielergeschiedenis en schudde het hele sport door elkaar. Casartelli was een veelbelovende jonge renner met een glorieuze toekomst voor zich. Zijn dood raakte niet alleen het wielrennen maar het ganse wereld en leidde tot veiligheidsverhogingen in wielerwedstrijden.", diff:3 },

  "HC065": { jaar:1998, cat:"Memorabel", renner:"Festina-affaire", nat:"🌍 Internationaal", race:"Tour de France (Doping schandaal)", kort:"Het grootste dopingschandaal in de wielergeschiedenis onthult systématische doping", lang:"De Festina-affaire van dat jaar was het grootste dopingschandaal in de wielergeschiedenis en ontbulde systématische doping op een schaal die niemand had gelijk. Het team Festina werd van de Tour verwijderd nadat hun soigneur werd betrapt met dopingmiddelen in zijn auto. Dit schandaal schudde het wielrennen door elkaar en leidde tot diepe vragen over de integriteit van het hele sport. De Festina-affaire markeerde een keerpunt in hoe doping in het wielrennen werd behandeld en hoe ernstig de controles werden verscherpt.", diff:3 },

  "HC066": { jaar:1999, cat:"Memorabel", renner:"Marco Pantani", nat:"🇮🇹 Italië", race:"Giro d'Italia (Uitsluiting wegens hemoglobine)", kort:"Een toprenner wordt uit de koers gezet wegens verdacht hoge hemoglobinenwaarden", lang:"Marco Pantani werd dat jaar uit de Giro d'Italia gezet wegens verdacht hoge hemoglobinenwaarden, wat duidt op mogelijke bloeddoping. Dit was een traumatische moment voor Pantani, die net de Giro domineerde en op weg was naar een overwinning. De uitsluiting zou Pantani's carrière ernstig beschadigen en maakte hem voorgoed tot een tragisch figuur in het wielrennen. Zijn mentale staat zou nooit herstellen van deze schande, ondanks dat hij later redenen zou vinden om zijn onschuld te bewijzen.", diff:3 },

  "HC067": { jaar:2006, cat:"Memorabel", renner:"Floyd Landis", nat:"🇺🇸 Verenigde Staten", race:"Tour de France (Doping test)", kort:"Een Amerikaanse Tourwinnaar test positief en verliest zijn titel", lang:"Floyd Landis testte dat jaar positief op verboden anabolen steroïden na het winnen van de Tour de France, wat een van de grote dopingschandalen in het wielrennen markeerde. Hoewel Landis aanvankelijk zijn onschuld beweerde en zelfs gewonnen te hebben, werd hij uiteindelijk gediskwalificeerd en verloor hij zijn Tourtitel. Dit schandaal ondersteepte de dopingproblemen in de professionele wielersport en leidde tot verdere vragen over de integriteit van de koers.", diff:3 },

  "HC068": { jaar:2010, cat:"Memorabel", renner:"Alberto Contador", nat:"🇪🇸 Spanje", race:"Tour de France (Clenbuterol test)", kort:"Een toprenner gaat door een dopingaffaire na een verdachte testuitslag", lang:"Alberto Contador testte dat jaar positief op clenbuterol, een verboden stof, maar beweert dat het van vervuilde biefstuk afkomstig was. Dit schandaal plaatste Contador jaren in juridische en publieke onzekerheid voordat hij uiteindelijk werd gediskwalificeerd. De casus Contador raakte diep in het hart van de wielersport en de vragen over doping die altijd aanwezig waren. Dit markeerde het begin van het einde van Contador's dominantie in het wielrennen.", diff:3 },

  "HC069": { jaar:2013, cat:"Memorabel", renner:"Lance Armstrong", nat:"🇺🇸 Verenigde Staten", race:"Wielrennen (Bekentenis)", kort:"Een voormalige Tour-kampioen bekent zijn dopinggebruik in een beroemd interview", lang:"Lance Armstrong gaf dat jaar eindelijk toe dat hij dopingmiddelen had gebruikt om zijn zeven Tourtitels te behalen. Dit was een shock voor het hele wielrennen en legde bloot hoe Armstrong decennia lang het systeem had bedrogen. Zijn bekentenis maakte duidelijk dat zijn Tourtitels - gezien als monuments van de wielrennen - onder vals pretense waren gewonnen. Armstrong's val van gratie was een van de grootste schandalen in de sportgeschiedenis en veranderde voorgoed het oog van het publiek op de wielrennen.", diff:3 },

  "HC070": { jaar:2015, cat:"Memorabel", renner:"Chris Froome", nat:"🇬🇧 Groot-Brittannië", race:"Tour de France (Bergrit te voet)", kort:"Een Tourwinnaar loopt bergop nadat zijn fiets stuk gaat - en wint toch", lang:"Chris Froome liep dat jaar bergop naar beneden nadat zijn fiets bij zijn schakeling stuk ging, maar klom daarna opnieuw op zijn reserve-fiets en bleef recht. Deze spectaculaire moment werd bont uitgemeten en inspireerde het hele wielrennen. Froome's mentale sterkte en doorzettingsvermogen in deze ongelooflijke situatie maakte hem tot een held. Dit moment werd snel iconisch en toonde de wilskracht van moderne wielrenners.", diff:2 },

  "HC071": { jaar:2020, cat:"Memorabel", renner:"Tadej Pogačar vs Primož Roglič", nat:"🇸🇮 Slovenië", race:"Tour de France (Slottijdrit)", kort:"Een jonge rivaal sleept de titel weg van een favorieet in de allerlaatste etappe", lang:"Tadej Pogačar sleepte dat jaar de Tourtitel weg van de favoriète Primož Roglič in een spectaculaire slottijdrit die het wielrennen in zijn greep hield. Dit was één van de meest dramatische momenten in recente Tourchiedenis, waarin Pogačar op zijn 21ste werkelijk domineerde. De slottijdrit tussen de twee Sloveense rivalen was een masterclass in wielrennen en veranderde alles in een moment.", diff:2 },

  "HC072": { jaar:2021, cat:"Memorabel", renner:"Mark Cavendish", nat:"🇬🇧 Groot-Brittannië", race:"Gent-Wevelgem (Merckx record)", kort:"Een Britse sprinter breekt het record van Merckx met zijn 35ste klassieke zege", lang:"Mark Cavendish brak dat jaar het record van Eddy Merckx door zijn 35ste klassieke zege te behalen, wat hem de meest gestage klassieke winnaar in het wielrennen maakte. Deze historische moment zorgde voor een staande ovatie voor de Britse sprinter die altijd als dominante coureur in het wielrennen werd beschouwd. Cavendish's record toonde zijn onvermoeibare doorzettingsvermogen en vastberadenheid gedurende een lange en prestijevolle carrière.", diff:2 },

  "HC073": { jaar:2021, cat:"Memorabel", renner:"Sonny Colbrelli", nat:"🇮🇹 Italië", race:"Parijs-Roubaix", kort:"Een renner lijdt een hartaanval direct na de finish", lang:"Sonny Colbrelli leed dat jaar direct na zijn zege in Parijs-Roubaix een medisch incident op toen zijn hart haperde. Dit was een schrikwekkend moment in het wielrennen dat aantoonde hoe fragiel menselijk lichaam kan zijn. Colbrelli overleefde het incident dankzij snelle medische hulp, maar het zorgde voor zorgen over de fysieke grenzen van professioneel wielrennen. Dit moment maakte duidelijk dat gezondheid belangrijker is dan prestaties.", diff:3 },

  "HC074": { jaar:2022, cat:"Memorabel", renner:"Remco Evenepoel", nat:"🇧🇪 België", race:"Vuelta + Olympische Spelen (Dubbel op hoogtepunt)", kort:"Een jong talent wint twee monumentale titels in dezelfde zomer", lang:"Remco Evenepoel won dat jaar zowel de Vuelta a España als het goud op de Olympische Spelen wegwedstrijd, wat een memorabel moment voor het wielrennen markeerde. Deze dubbel op het hoogtepunt van het seizoen toonde Evenepoel's uitzonderlijke talent en mentale sterkte op jonge leeftijd. Voor België was dit een historisch moment dat het land opnieuw op de wielerkaart zette. Evenepoel's prestatie inspireerde toekomstige generaties en toonde dat ook jonge talenten monumentale titels konden winnen.", diff:2 },

  "HC075": { jaar:2024, cat:"Memorabel", renner:"Jonas Vingegaard", nat:"🇫🇷 Frankrijk", race:"Tour de France (Comeback na blessure)", kort:"Een verleterde renner keert terug en wint opnieuw de Tour", lang:"Jonas Vingegaard maakte dat jaar een spectaculaire comeback na een zware blessure en won opnieuw de Tour de France, wat hem in het boek van memorials zette. Met zijn mentale sterkte en vastberadenheid overwon hij niet alleen zijn fysieke beperkingen maar ook zijn rivalen. Dit comeback-verhaal inspireerde het hele wielrennen en toonde de kracht van menselijk wilsvermogen. Vingegaard's derde Tourtitel was het meest emotionele van zijn carrière en maakte hem tot een legende in het wielrennen.", diff:3 },

  "HC076": { jaar:1996, cat:"Memorabel", renner:"Bjarne Riis", nat:"🇩🇰 Denemarken", race:"Tour de France (Doping bekentenis jarenlater)", kort:"Een voormalige Tourwinnaar bekent jaren later dat hij doping gebruikte", lang:"Bjarne Riis bekende dat jaar, meer dan tien jaar later, dat hij dat jaar EPO had gebruikt om zijn Tourtitel te behalen. Deze bekentenis schudde het wielrennen door elkaar en ontmaskerde de dopingproblemen van de jaren. Riis' bekentenis toonde aan dat velen in het wielrennen aan doping hadden gedaan maar er jarenlang mee wegkwamen. Dit zou het begin zijn van een lange periode van doping-schandalen in het wielrennen.", diff:3 },

  "HC077": { jaar:2003, cat:"Memorabel", renner:"Lance Armstrong", nat:"🇺🇸 Verenigde Staten", race:"Tour de France (Beloki crash)", kort:"Een kampioen ontsnapt aan een ernstige valpartij en wint toch", lang:"Lance Armstrong ontsnapte dat jaar aan een ernstige valpartij toen Beloki voor hem viel, maar wist door zijn uitzonderlijke rijvaardigheden toch zijn koers voort te zetten. Dit moment toonde Armstrong's fysieke skills en mentale veerkracht onder druk. De crash was dramatisch maar Armstrong's vermogen om erdoorheen te rijden maakte hem tot een held in veel ogen. Dit moment werd lang herinnerd als één van de meest spectaculaire momenten in de Tourgeschiedenis.", diff:2 },

  "HC078": { jaar:2012, cat:"Memorabel", renner:"Team Sky", nat:"🇬🇧 Groot-Brittannië", race:"Tour de France (Bus incident)", kort:"Een teambus zit in een ongeval op een Alpenbeklimming", lang:"In zat de Team Sky-bus in een ernstig verkeersongeval op een Alpenbeklimming tijdens de Tour de France. Dit was een schokkend moment dat aantoonde hoe onveilig het wielrennen kan zijn. Gelukkig raakten de renners zelf niet ernstig gewond, maar het incident onderstreepte de noodzaak voor verbeterde veiligheidsmiddelen in het wielrennen. Dit moment leidde tot verdere discussies over veiligheid in de wielersport.", diff:2 },

  "HC079": { jaar:2018, cat:"Memorabel", renner:"Chris Froome", nat:"🇬🇧 Groot-Brittannië", race:"Giro d'Italia (Bergdaling incident)", lang:"Chris Froome had dat jaar een schrikwekkend incident op een bergdaling in de Giro d'Italia toen hij zijn kontrolle verloor. Dit moment deed vragen rijzen over veiligheid op gevaarlijke bergdaling en de mentale tol van het wielrennen. Froome's vermogen om te herstellen toonde echter zijn mentale sterkte.", diff:2 },

  "HC080": { jaar:2019, cat:"Memorabel", renner:"Chris Froome", nat:"🇬🇧 Groot-Brittannië", race:"Critérium du Dauphiné (Crash)", kort:"Een toprenner crasht zwaar en verliest vertrouwen in zijn voorbereiding", lang:"Chris Froome had dat jaar een zware crash in de Critérium du Dauphiné, de voorbereiding op de Tour de France. Deze crash beschadigde niet alleen zijn lichaam maar ook zijn mentale voorbereiding. Dit incident markeerde het begin van het einde van Froome's dominantie in het wielrennen, want hij kon nooit volledig herstellen van de fysieke en mentale impact van de valpartij.", diff:3 },

  "HC081": { jaar:2022, cat:"Memorabel", renner:"Jonas Vingegaard", nat:"🇫🇷 Frankrijk", race:"Tour de France (Col du Granon aanval)", kort:"Een Fransman rijdt een dappere aanval op Col du Granon en pakt de Tour", lang:"Jonas Vingegaard voerde dat jaar een dappere aanval uit op Col du Granon, waar hij Tadej Pogačar attackeerde en van zich afhielp. Dit moment markeerde het keerpunt in Vingegaard's Tourcanpagne en toonde zijn mentale sterkte. De aanval op Col du Granon wordt herinnerd als één van de meest iconische momenten in recente Tourchiedenis.", diff:3 },

  "HC082": { jaar:2017, cat:"Memorabel", renner:"Peter Sagan", nat:"🇸🇰 Slowakije", race:"Wereldkampionschap (Disqualificatie wegens bumptrack met Cavendish)", kort:"Een wereldkampioen wordt gediskwalificeerd voor een fout tegen zijn rivaal", lang:"Peter Sagan werd dat jaar gediskwalificeerd van het Wereldkampioenschap Weg vanwege een bumptrack tegen Mark Cavendish in de spurt. Dit was een controversiële beslissing die veel discussie veroorzaakte in het wielrennen. Sagan's disqualificatie werd door velen gezien als te zwaar gestraft en het incident toonde dat de UCI regelgevingen discutabel waren.", diff:2 },

  "HC083": { jaar:2014, cat:"Memorabel", renner:"Vincenzo Nibali", nat:"🇮🇹 Italië", race:"Tour de France (Tourmalet solo)", kort:"Een Italiaan rijdt solo weg op Tourmalet en dominaert bergop", lang:"Vincenzo Nibali voerde dat jaar een legendaire solo-aanval uit op Tourmalet, waar hij zijn concurrenten volledig vernietigd reed. Dit moment werd een van de meest iconische uitvoeringen van bergklimmen in de Tourgeschiedenis. Nibali's vermogen om dit bergmonument solo aan te vallen en te domineren toonde waarom hij de beste bergklimmer van zijn generatie was.", diff:2 },

  "HC084": { jaar:1990, cat:"Memorabel", renner:"Greg LeMond", nat:"🇺🇸 Verenigde Staten", race:"Tour de France (Comeback na schietwonde)", kort:"Een Amerikaanse kampioen keert terug na een schietwonde en wint de Tour", lang:"Greg LeMond maakte dat jaar een opmerkelijk comeback en won de Tour de France na te zijn neergeschoten in een jachtongeval. Dit was een van de meest inspirerende comeback-verhalen in de wielergeschiedenis. LeMond's mentale sterkte en vastberadenheid na zo'n trauma toonden de kracht van menselijk wilsvermogen en inspireerden velen.", diff:3 },

  "HC085": { jaar:1992, cat:"Grote Ronde", renner:"Miguel Induráin", nat:"🇪🇸 Spanje", race:"Giro d'Italia", kort:"Een Spaan domineert de Italiaanse ronde", lang:"Miguel Induráin won dat jaar de Giro d'Italia met absolute dominantie en controleerde de koers op elk moment. Dit was het eerste deel van zijn Giro-Tour dubbel dat jaar, wat zijn fenomenale vorm aantoonde. Induráin's Giro-zege toonde aan dat hij niet alleen in de Tour dominant was maar ook in andere grote rondes.", diff:2 },

  "HC086": { jaar:1993, cat:"Grote Ronde", renner:"Tony Rominger", nat:"🇨🇭 Zwitserland", race:"Vuelta a España", kort:"Een Zwitser wint de Spaanse grote ronde", lang:"Tony Rominger won dat jaar de Vuelta a España en voegde deze grote ronde toe aan zijn palmares. Met zijn sterkte in bergen en mentale focus controleerde Rominger de Vuelta. Dit was een van de hoogtepunten van Rominger's carrière en plaatste hem onder de topkandidaten voor grote rondes.", diff:2 },

  "HC087": { jaar:1994, cat:"Grote Ronde", renner:"Evgeny Berzin", nat:"🇷🇺 Rusland", race:"Giro d'Italia", kort:"Een Russische renner wint de Giro op jonge leeftijd", lang:"Evgeny Berzin won dat jaar de Giro d'Italia op jonge leeftijd en toonde aanmerkelijk talent. Met zijn explosieve vermogen en mentale sterkte domineerde Berzin de Italiaanse koers. Dit was het hoogtepunt van Berzin's carrière, hoewel doping-beschuldigingen later zijn reputatie beschadigden.", diff:2 },

  "HC088": { jaar:2009, cat:"Grote Ronde", renner:"Alberto Contador", nat:"🇪🇸 Spanje", race:"Giro d'Italia", kort:"Een Spaanse kampioen domineert de Italiaanse koers", lang:"Alberto Contador won dat jaar de Giro d'Italia en domineerde de Italiaanse koers met zijn karakteristieke aanvallen. Met zijn explosieve vermogen in bergen en tactische inzicht controleerde Contador de Giro. Dit was één van de meest dominante Giro-performances in jaren en plaatste Contador als één van de beste renners van zijn generatie.", diff:2 },

  "HC089": { jaar:2011, cat:"Grote Ronde", renner:"Samantha Cobo", nat:"🇬🇧 Groot-Brittannië", race:"Vuelta a España", kort:"Een Britse renner wint de Spaanse grote ronde", lang:"Samantha Cobo won dat jaar de Vuelta a España en voegde deze grote ronde toe aan haar palmares. Met haar sterkte en mentale focus controleerde Cobo de Vuelta. Dit was een van de hoogtepunten van Cobo's carrière en plaatste haar onder de toprenners in grote rondes.", diff:2 },

  "HC090": { jaar:2016, cat:"Grote Ronde", renner:"Nairo Quintana", nat:"🇨🇴 Colombia", race:"Vuelta a España", kort:"Een Colombiaan wint de Spaanse ronde", lang:"Nairo Quintana won dat jaar de Vuelta a España en voegde deze grote ronde toe aan zijn palmares. Met zijn explosieve bergvermogen en mentale sterkte domineerde Quintana de Vuelta. Dit was het hoogtepunt van Quintana's Vuelta-carrière en toonde waarom hij één van de beste bergklimmers was.", diff:2 },

  "HC091": { jaar:2023, cat:"Grote Ronde", renner:"Sepp Kuss", nat:"🇺🇸 Verenigde Staten", race:"Vuelta a España", kort:"Een Amerikaanse renner domineert en wint historisch de Vuelta", lang:"Sepp Kuss schreef dat jaar wielergeschiedenis door als eerste Amerikaanse renner de Vuelta a España te winnen. Met zijn sterkte in bergen en mentale focus controleerde Kuss de Spaanse koers. Dit was een monumentaal moment voor het Amerikaanse wielrennen en inspireerde een hele generatie.", diff:3 },

  "HC092": { jaar:1993, cat:"Klassiek", renner:"Gilbert Duclos-Lassalle", nat:"🇫🇷 Frankrijk", race:"Parijs-Roubaix", kort:"Een Franse renner wint klassiek op latere leeftijd", lang:"Gilbert Duclos-Lassalle won Parijs-Roubaix dat jaar op latere leeftijd en toonde dat klassieke renners hun vermogen behouden. Met zijn sterkte op kasseien domineerde Duclos-Lassalle de Hel van het Noorden. Dit was een van de hoogtepunten van zijn lange carrière en toonde waarom hij een klassieker was.", diff:2 },

  "HC093": { jaar:1997, cat:"Klassiek", renner:"Frédéric Guesdon", nat:"🇫🇷 Frankrijk", race:"Parijs-Roubaix", kort:"Een Fransman domineert de kasseien van Roubaix", lang:"Frédéric Guesdon won Parijs-Roubaix dat jaar en domineerde de Hel van het Noorden met zijn sterkte. Met zijn vermogen op kasseien controleerde Guesdon de koers. Dit was het hoogtepunt van Guesdon's carrière in de klasseken.", diff:2 },

  "HC094": { jaar:2001, cat:"Klassiek", renner:"Johan Museeuw", nat:"🇧🇪 België", race:"Parijs-Roubaix", kort:"Een veteraan van klassiek wielrennen wint opnieuw", lang:"Johan Museeuw won Parijs-Roubaix dat jaar en voegde zijn tweede zege toe aan dit monument. Met zijn karakteristieke sterkte domineerde Museeuw opnieuw de kasseien. Dit was later in zijn carrière maar toonde dat Museeuw nog steeds competitief was op het meest kasseien.", diff:2 },

  "HC095": { jaar:2004, cat:"Klassiek", renner:"Magnus Bäckstedt", nat:"🇸🇪 Zweden", race:"Parijs-Roubaix", kort:"Een Zweedse renner wint de Hel van het Noorden", lang:"Magnus Bäckstedt won Parijs-Roubaix dat jaar en plaatste zich onder de winnaars van dit monument. Met zijn sterkte op kasseien controleerde Bäckstedt de Hel van het Noorden. Dit was het hoogtepunt van Bäckstedt's carrière en toonde zijn klassieke vermogen.", diff:2 },

  "HC096": { jaar:2002, cat:"Klassiek", renner:"Mario Cipollini", nat:"🇮🇹 Italië", race:"Milaan-San Remo", kort:"Een Italiaanse sprinter domineert in Milaan-San Remo", lang:"Mario Cipollini won Milaan-San Remo dat jaar en domineerde deze langste klassieke rit. Met zijn sprintkracht domineerde Cipollini de massaspurt. Dit was een van de hoogtepunten van Cipollini's carrière in de klasseken.", diff:2 },

  "HC097": { jaar:2009, cat:"Klassiek", renner:"Mark Cavendish", nat:"🇬🇧 Groot-Brittannië", race:"Milaan-San Remo", kort:"Een Britse sprinter wint de klassieke sprint", lang:"Mark Cavendish won Milaan-San Remo dat jaar en domineerde deze langste klassieke rit. Met zijn sprintkracht en timing controleerde Cavendish de massaspurt. Dit was één van de eerste grote klassieke zeges van Cavendish's carrière.", diff:2 },

  "HC098": { jaar:2019, cat:"Klassiek", renner:"Philippe Gilbert", nat:"🇧🇪 België", race:"Parijs-Roubaix", kort:"Een Belgische klassieker wint opnieuw op latere leeftijd", lang:"Philippe Gilbert won Parijs-Roubaix dat jaar op latere leeftijd en toonde dat hij nog steeds competitief was in de klasseken. Met zijn karakteristieke vermogen domineerde Gilbert opnieuw de kasseien. Dit was het hoogtepunt van Gilberts latere carrière en toonde zijn doorzettingsvermogen.", diff:3 },

  "HC099": { jaar:1990, cat:"Wereldkampioenschap", renner:"Eddy Dhaenens", nat:"🇧🇪 België", race:"Wereldkampionschap Weg", kort:"Een Belgische renner wint het Wereldkampioenschap", lang:"Eddy Dhaenens won dat jaar het Wereldkampioenschap Weg en behaalde de meest geprezen titel in het wielrennen. Met zijn klassieke vermogen domineerde Dhaenens het WK-parcours. Dit was het hoogtepunt van Dhaenens' carrière en plaatste hem onder de allergrootsten.", diff:2 },

  "HC100": { jaar:1995, cat:"Wereldkampioenschap", renner:"Abraham Olano", nat:"🇪🇸 Spanje", race:"Wereldkampionschap Weg", kort:"Een Spaanse renner wint de regenboogtrui", lang:"Abraham Olano won dat jaar het Wereldkampioenschap Weg en behaalde de meest geprezen titel in het wielrennen. Met zijn sterkte domineerde Olano het WK-parcours. Dit was het hoogtepunt van Olano's carrière en plaatste hem permanent onder de allergrootsten.", diff:2 },

  "HC101": { jaar:1997, cat:"Wereldkampioenschap", renner:"Laurent Brochard", nat:"🇫🇷 Frankrijk", race:"Wereldkampionschap Weg", kort:"Een Fransman wint het Wereldkampioenschap", lang:"Laurent Brochard won dat jaar het Wereldkampioenschap Weg en behaalde de meest geprezen titel in het wielrennen. Met zijn vermogen domineerde Brochard het WK-parcours. Dit was het hoogtepunt van Brochard's carrière en plaatste hem onder de allergrootsten.", diff:2 },

  "HC102": { jaar:2003, cat:"Wereldkampioenschap", renner:"Igor Astarloa", nat:"🇪🇸 Spanje", race:"Wereldkampionschap Weg", kort:"Een Spaanse renner wint de regenboogtrui", lang:"Igor Astarloa won dat jaar het Wereldkampioenschap Weg en behaalde de meest geprezen titel in het wielrennen. Met zijn sterkte domineerde Astarloa het WK-parcours. Dit was het hoogtepunt van Astarloa's carrière en plaatste hem onder de allergrootsten.", diff:2 },

  "HC103": { jaar:2004, cat:"Wereldkampioenschap", renner:"Óscar Freire", nat:"🇪🇸 Spanje", race:"Wereldkampionschap Weg (3de titel)", kort:"Een Spaanse sprinter voegt zijn derde titel toe", lang:"Óscar Freire won dat jaar zijn derde Wereldkampioenschap Weg en plaatste zich onder de allergrootsten met meerdere WK-titels. Met zijn sprintkracht domineerde Freire het WK-parcours. Dit was het hoogtepunt van Freire's carrière en toonde zijn uitzonderlijke sprinttalent.", diff:2 },

  "HC104": { jaar:2006, cat:"Wereldkampioenschap", renner:"Danilo Bettini", nat:"🇮🇹 Italië", race:"Wereldkampionschap Weg (Salzburg)", kort:"Een Italiaanse renner wint het WK op moeilijk parcours", lang:"Danilo Bettini won dat jaar het Wereldkampioenschap Weg in Salzburg en behaalde de meest geprezen titel in het wielrennen. Met zijn vermogen domineerde Bettini het moeilijke bergachtige WK-parcours. Dit was het hoogtepunt van Bettini's carrière en plaatste hem permanent onder de allergrootsten.", diff:2 },

  "HC105": { jaar:2007, cat:"Wereldkampioenschap", renner:"Danilo Bettini", nat:"🇮🇹 Italië", race:"Wereldkampionschap Weg (Stuttgart)", kort:"Dezelfde Italiaan herhaalt zijn succes", lang:"Danilo Bettini herhaalde dat jaar zijn Wereldkampioenschap-succes en behaalde zijn tweede regenboogtrui. Met zijn karakteristieke vermogen domineerde Bettini opnieuw het WK-parcours. Deze tweede WK-titel toonde zijn uitzonderlijke talent en plaatste hem permanent onder de allergrootsten.", diff:2 },

  "HC106": { jaar:2010, cat:"Wereldkampioenschap", renner:"Thor Hushovd", nat:"🇳🇴 Noorwegen", race:"Wereldkampionschap Weg", kort:"Een Noors talent wint het Wereldkampioenschap", lang:"Thor Hushovd won dat jaar het Wereldkampioenschap Weg en behaalde de meest geprezen titel in het wielrennen. Met zijn veelzijdige vermogen domineerde Hushovd het WK-parcours. Dit was het hoogtepunt van Hushovd's carrière en plaatste hem permanent onder de allergrootsten.", diff:2 },

  "HC107": { jaar:2013, cat:"Wereldkampioenschap", renner:"Rui Costa", nat:"🇵🇹 Portugal", race:"Wereldkampionschap Weg (Florence)", kort:"Een Portugees kampioen wint de regenboogtrui in Florence", lang:"Rui Costa won dat jaar het Wereldkampioenschap Weg in Florence en behaalde de meest geprezen titel in het wielrennen. Met zijn klassieke vermogen domineerde Costa het WK-parcours. Dit was het hoogtepunt van Costa's carrière en plaatste hem permanent onder de allergrootsten.", diff:2 },

  "HC108": { jaar:2014, cat:"Wereldkampioenschap", renner:"Michał Kwiatkowski", nat:"🇵🇱 Polen", race:"Wereldkampionschap Weg", kort:"Een Pools talent wint het Wereldkampioenschap", lang:"Michał Kwiatkowski won dat jaar het Wereldkampioenschap Weg en behaalde de meest geprezen titel in het wielrennen. Met zijn veelzijdig vermogen domineerde Kwiatkowski het WK-parcours. Dit was het begin van Kwiatkowski's lange periode van dominantie in het wielrennen.", diff:2 },

  "HC109": { jaar:2018, cat:"Wereldkampioenschap", renner:"Alejandro Valverde", nat:"🇪🇸 Spanje", race:"Wereldkampionschap Weg (Innsbruck)", kort:"Een Spaanse veteraan wint eindelijk de regenboogtrui", lang:"Alejandro Valverde won dat jaar het Wereldkampioenschap Weg in Innsbruck en behaalde eindelijk de meest geprezen titel in het wielrennen. Na jaren van topprestatties won Valverde de regenboogtrui op latere leeftijd. Dit was een fitting einde op zijn lange en succesvolle carrière.", diff:2 },

  "HC110": { jaar:2007, cat:"Memorabel", renner:"Michael Rasmussen", nat:"🇩🇰 Denemarken", race:"Tour de France (Verwijdering)", kort:"Een topleider wordt uit de Tour verwijderd wegens dopingschandaal", lang:"Michael Rasmussen werd dat jaar uit de Tour de France verwijderd nadat bleek dat hij geen begeleiding had gegeven over zijn verblijfplaats voor dopingtests. Dit schandaal schudde de Tour door elkaar en ondersteepte de dopingproblemen in het wielrennen. Rasmussen's verwijdering gebeurde op een moment dat hij eigenlijk de Tour leek te winnen.", diff:3 },

  "HC111": { jaar:2012, cat:"Grote Ronde", renner:"Ryder Hesjedal", nat:"🇨🇦 Canada", race:"Giro d'Italia", kort:"Een Canadese renner wint zijn eerste grote ronde", lang:"Ryder Hesjedal won dat jaar de Giro d'Italia en behaalde zijn eerste grote ronde-titel. Met zijn sterkte in bergen en mentale focus domineerde Hesjedal de Italiaanse koers. Dit was het hoogtepunt van Hesjedal's carrière en plaatste hem permanent onder de toprenners in grote rondes.", diff:2 },

  "HC112": { jaar:2022, cat:"Klassiek", renner:"Biniam Girmay", nat:"🇪🇷 Eritrea", race:"Gent-Wevelgem", kort:"Een jong talent uit Eritrea wint voor het eerste keer een klassieke rit", lang:"Biniam Girmay won dat jaar Gent-Wevelgem en behaalde zijn eerste grote klassieke zege. Met zijn explosieve vermogen domineerde Girmay het klassieke parcours. Dit was het begin van Girmay's dominantie in het wielrennen en plaatste hem als een toekomstige ster. Voor Eritrea was dit een historisch moment dat het land op de wielerkaart zette.", diff:2 },

  "HC113": { jaar:2024, cat:"Memorabel", renner:"Remco Evenepoel", nat:"🇧🇪 België", race:"Olympische Spelen (Dubbel), road race en tijdrit", kort:"Een jong talent wint beide gouden medailles op de Olympische Spelen", lang:"Remco Evenepoel schreef dat jaar wielergeschiedenis door zowel goud te winnen in de wegwedstrijd als de tijdrit op de Olympische Spelen. Dit was een monumentale dubbel die zeer weinig renners hebben kunnen bereiken. Met zijn titanische kracht en veelzijdig vermogen domineerde Evenepoel beide olympische wedstrijden. Deze dubbel plaatste Evenepoel permanent under de allergrootsten en toonde waarom hij de meest complete renner van zijn generatie is.", diff:2 }
};
