export const MOMENTEN_AJAX = {
  "AJ001": { jaar:1995, cat:"Landstitel", renner:"Louis van Gaal", nat:"🇳🇱 Nederland", race:"Eredivisie", kort:"Onder een Nederlandse trainer prolongeert een jonge, aanvallende ploeg moeiteloos de landstitel, terwijl het Europese hoogtepunt van het seizoen nog moet komen", lang:"Ajax werd onder Louis van Gaal voor het tweede jaar op rij landskampioen, met een basiself vol eigen jeugdproducten als de gebroeders De Boer, Clarence Seedorf en Patrick Kluivert. De ploeg speelde herkenbaar aanvallend voetbal en had de titelstrijd in Nederland al vroeg in het seizoen beslist. Terwijl de Eredivisie nauwelijks nog spanning kende, groeide het elftal ondertussen uit tot een van de sterkste ploegen van Europa. Dat seizoen zou niet bij de landstitel blijven, want er lonkte ook internationaal succes.", diff:2 },

  "AJ002": { jaar:1996, cat:"Landstitel", renner:"Louis van Gaal", nat:"🇳🇱 Nederland", race:"Eredivisie", kort:"Een trainer sluit zijn gouden tijdperk af met een derde landstitel op rij, iets wat de club sinds de jaren zestig niet meer was gelukt", lang:"Ajax pakte dat jaar zijn derde landstitel op rij onder Louis van Gaal, de eerste keer sinds de late jaren zestig dat de club drie kampioenschappen achter elkaar behaalde. De selectie met onder anderen Edgar Davids, Michael Reiziger en Jari Litmanen bleef ondanks internationale belangstelling nog grotendeels bij elkaar. Het zou echter de laatste titel van het Van Gaal-tijdperk worden, want na dat seizoen vertrok de trainer naar Barcelona. Kort daarna viel de succesvolle generatie ook snel uiteen door vertrekkende sterspelers.", diff:2 },

  "AJ003": { jaar:1998, cat:"Landstitel", renner:"Ajax", nat:"🇳🇱 Nederland", race:"Eredivisie", kort:"Een ploeg zonder de meeste sterren van weleer verrast door alsnog een overtuigende dubbel te pakken in binnenlands voetbal", lang:"Ajax werd dat jaar landskampioen en pakte bovendien de KNVB-beker, een overtuigende dubbel nadat de gouden generatie van Van Gaal grotendeels uit elkaar was gevallen. Spelers als Davids, Kluivert, Reiziger en Bogarde waren inmiddels vertrokken, maar met onder meer de jonge Edwin van der Sar onder de lat en een nieuwe lichting bleef de club aan de top staan. De bekerfinale werd met liefst vijf doelpunten verschil gewonnen. Deze titel bewees dat Ajax ook na het afscheid van zijn absolute wereldsterren nog altijd de dienst kon uitmaken in Nederland.", diff:2 },

  "AJ004": { jaar:2002, cat:"Landstitel", renner:"Ronald Koeman", nat:"🇳🇱 Nederland", race:"Eredivisie", kort:"Een kersverse trainer wint direct in zijn eerste volle seizoen de landstitel met een ploeg die ook de nationale beker meepakt", lang:"Ronald Koeman leidde Ajax dat jaar naar de landstitel in zijn eerste volle seizoen als hoofdtrainer, gecombineerd met een bekerzege op FC Utrecht na verlenging. De ploeg draaide op een mix van ervaren namen en jong talent, met een besliste rol voor een nieuwe spits die net was overgekomen uit Zweden. Onder Koeman werd het elftal opnieuw herkenbaar als een dominante factor in de Eredivisie, na enkele wisselvallige seizoenen. Deze titel legde de basis voor een periode waarin Ajax weer regelmatig om de prijzen streed.", diff:2 },

  "AJ005": { jaar:2004, cat:"Landstitel", renner:"Ronald Koeman", nat:"🇳🇱 Nederland", race:"Eredivisie", kort:"Dezelfde trainer pakt zijn tweede landstitel voordat hij korte tijd later voor een avontuur in Spanje kiest", lang:"Ajax werd dat jaar voor de tweede keer onder Ronald Koeman landskampioen, andermaal met een ploeg die leunde op een sterke defensie en efficiënt aanvalsspel. Het seizoen verliep ondanks interne onrust rond een aantal sterspelers uiteindelijk voorspoedig genoeg om de titel veilig te stellen. Niet lang na deze tweede titel vertrok Koeman naar Benfica, waarmee een succesvolle periode aan het Museumplein ten einde kwam. De titel bleef voorlopig de laatste landstitel voor Ajax gedurende een aantal magere jaren daarna.", diff:2 },

  "AJ006": { jaar:2011, cat:"Landstitel", renner:"Frank de Boer", nat:"🇳🇱 Nederland", race:"Eredivisie", kort:"Een clubicoon uit de gouden jaren negentig grijpt in zijn eerste volledige seizoen als trainer meteen de titel na jaren van Ajax-loze kampioenschappen", lang:"Frank de Boer, die halverwege een eerder seizoen als hoofdtrainer was aangesteld, leidde Ajax dat jaar naar zijn eerste landstitel in zeven jaar tijd. Met spelers als Luis Suárez, Jan Vertonghen en Toby Alderweireld vormde De Boer een ploeg die zowel technisch als fysiek de Eredivisie domineerde. Deze titel doorbrak een lange periode waarin andere clubs steeds met de schaal gingen strijken. Niemand kon toen nog vermoeden dat dit nog maar het begin was van een reeks landstitels onder deze trainer.", diff:2 },

  "AJ007": { jaar:2012, cat:"Landstitel", renner:"Frank de Boer", nat:"🇳🇱 Nederland", race:"Eredivisie", kort:"Dezelfde trainer prolongeert zijn eerste titel met een ploeg waarin twee Belgische verdedigers een hoofdrol spelen", lang:"Ajax werd dat jaar voor het tweede jaar op rij landskampioen onder Frank de Boer, ditmaal met een centrale verdediging gevormd door de Belgen Jan Vertonghen en Toby Alderweireld, twee producten van de eigen jeugdopleiding. De ploeg bleef bouwen op een combinatie van eigen kweek en gerichte aankopen. Deze tweede opeenvolgende titel toonde aan dat het succes van het voorgaande seizoen geen toevalstreffer was geweest. Het legde bovendien de basis voor wat zou uitgroeien tot een langere periode van dominantie in Nederland.", diff:2 },

  "AJ008": { jaar:2013, cat:"Landstitel", renner:"Frank de Boer", nat:"🇳🇱 Nederland", race:"Eredivisie", kort:"Een derde landstitel op rij levert de trainer een prijs voor beste coach van het land op", lang:"Ajax pakte dat jaar zijn derde landstitel op rij onder Frank de Boer, die voor deze prestatie werd bekroond met de Rinus Michels Award als trainer van het jaar. De ploeg bleef ondanks vertrekkende sterspelers steeds opnieuw scherp staan onder de nieuwe technische leiding. Met deze titel evenaarde De Boer als trainer al een deel van zijn eigen erelijst als speler uit de jaren negentig. De vraag begon te leven of hij het unieke record van vier titels op rij kon gaan verbreken.", diff:2 },

  "AJ009": { jaar:2014, cat:"Landstitel", renner:"Frank de Boer", nat:"🇳🇱 Nederland", race:"Eredivisie", kort:"Een trainer schrijft geschiedenis met een unieke vierde landstitel op rij, een prestatie die niemand bij de club hem had voorgedaan", lang:"Frank de Boer werd dat jaar voor de vierde keer op rij landskampioen met Ajax, een unicum in de clubgeschiedenis dat nog niemand hem had voorgedaan als trainer. Met deze vierde titel liet De Boer een stempel achter die zijn eigen succesvolle spelerscarrière uit de jaren negentig evenaarde. De ploeg bleef ondanks een voortdurende uitstroom van talent naar het buitenland telkens weer de sterkste in Nederland. Deze prestatie bevestigde definitief de status van De Boer als een van de succesvolste trainers uit de clubhistorie.", diff:1 },

  "AJ010": { jaar:2019, cat:"Landstitel", renner:"Erik ten Hag", nat:"🇳🇱 Nederland", race:"Eredivisie", kort:"Tien dagen na het pakken van de beker wordt de titel op de valreep veiliggesteld met een monsterzege op de slotdag bij een subtopper", lang:"Ajax veroverde dat jaar de landstitel met een klinkende 1-4 zege op de slotspeeldag bij De Graafschap, net op tijd om PSV op doelsaldo af te troeven. Onder de nog relatief jonge trainer Erik ten Hag combineerde de ploeg met sterspelers als Matthijs de Ligt en Frenkie de Jong deze titel met de KNVB-beker eerder dat seizoen. Het seizoen kreeg internationaal nog meer glans door een sensationele Europese campagne die tot diep in het voorjaar duurde. Deze dubbel gold als het eerste grote bewijs dat Ten Hag een nieuwe generatie topspelers had opgebouwd.", diff:1 },

  "AJ011": { jaar:2021, cat:"Landstitel", renner:"Erik ten Hag", nat:"🇳🇱 Nederland", race:"Eredivisie", kort:"In een seizoen zonder toeschouwers op de tribunes wordt de landstitel alsnog met een ruime voorsprong veiliggesteld", lang:"Ajax werd dat jaar landskampioen onder Erik ten Hag, in een seizoen dat grotendeels zonder publiek werd afgewerkt vanwege de coronapandemie. Ondanks de vreemde omstandigheden domineerde de ploeg de Eredivisie met overtuigend spel en een ruime voorsprong op de concurrentie. Spelers als Dusan Tadic en de opkomende Ryan Gravenberch speelden een hoofdrol in het seizoen. Deze titel bevestigde dat de wederopbouw onder Ten Hag na het vertrek van meerdere sterspelers geslaagd was.", diff:2 },

  "AJ012": { jaar:2022, cat:"Landstitel", renner:"Erik ten Hag", nat:"🇳🇱 Nederland", race:"Eredivisie", kort:"Een trainer pakt zijn laatste grote prijs bij de club voordat hij voor een avontuur in de Premier League kiest", lang:"Ajax werd dat jaar voor de derde keer onder Erik ten Hag landskampioen, de zesendertigste landstitel in de clubgeschiedenis. Het seizoen bevestigde nogmaals de dominantie van de ploeg in Nederland, met een aanval die met afstand de meeste doelpunten van de competitie produceerde. Kort na deze titel maakte Ten Hag bekend dat hij Ajax zou verlaten voor Manchester United, waarmee een succesvolle periode werd afgesloten. Voor spelers als Antony en Lisandro Martínez bleek het de laatste prijs die zij met de club wonnen voordat ook zij vertrokken.", diff:2 },

  "AJ013": { jaar:1998, cat:"Beker", renner:"Ajax", nat:"🇳🇱 Nederland", race:"KNVB Beker", kort:"Een landelijke rivaal wordt in de finale met een vernietigende vijf doelpunten verschil opzijgezet", lang:"Ajax won die editie van de KNVB-beker met een overtuigende 5-0 zege op PSV in de finale, wat samen met de landstitel dat seizoen voor een fraaie dubbel zorgde. De wedstrijd liet zien dat de ploeg ondanks het vertrek van veel sterspelers uit het Van Gaal-tijdperk nog altijd tot grote overwinningen in staat was. Het was een van de ruimste bekerfinale-uitslagen van de jaren negentig. Deze prestatie bevestigde dat de vernieuwde selectie klaar was om de erfenis van de gouden generatie voort te zetten.", diff:2 },

  "AJ014": { jaar:1999, cat:"Beker", renner:"Ajax", nat:"🇳🇱 Nederland", race:"KNVB Beker", kort:"Een minder succesvol competitieseizoen wordt goedgemaakt met een tweede bekerzege op rij tegen een club uit Limburg", lang:"Ajax veroverde dat jaar opnieuw de KNVB-beker, met een 2-0 zege op Fortuna Sittard in de finale. De prijs gold als een welkome compensatie in een seizoen waarin de landstitel niet binnen bereik lag en de club bovendien te maken kreeg met interne onrust rond enkele sterspelers. Toch bewees de ploeg in het bekertoernooi haar klasse door het toernooi ongeslagen te doorlopen. Deze bekerzege hielp om het seizoen alsnog met een trofee af te sluiten.", diff:3 },

  "AJ015": { jaar:2002, cat:"Beker", renner:"Ajax", nat:"🇳🇱 Nederland", race:"KNVB Beker", kort:"Een gouden doelpunt van een pas gearriveerde Zweedse spits in de verlenging beslist een spannende bekerfinale", lang:"Ajax won die editie van de KNVB-beker na verlenging van FC Utrecht, met een beslissend gouden doelpunt van de kort daarvoor overgekomen Zweedse spits Zlatan Ibrahimović. De zege werd gecombineerd met de landstitel van datzelfde seizoen, wat een fraaie dubbel opleverde onder trainer Ronald Koeman. Het gouden doelpunt-systeem, destijds nog in gebruik in het Nederlandse bekertoernooi, zorgde voor een extra dramatisch slot van de finale. Voor de jonge Ibrahimović was het een vroeg hoogtepunt in zijn eerste seizoen bij de club.", diff:2 },

  "AJ016": { jaar:2006, cat:"Beker", renner:"Ajax", nat:"🇳🇱 Nederland", race:"KNVB Beker", kort:"In een finale tussen twee traditionele topclubs trekt de ploeg uit Amsterdam met een doelpunt verschil aan het langste eind", lang:"Ajax won de bekerfinale van dat seizoen met 2-1 van PSV, in een affiche tussen twee van de traditioneel sterkste clubs van Nederland. De zege gaf de ploeg een prijs in een seizoen waarin de landstitel wederom niet haalbaar bleek. Het toernooi bevestigde dat Ajax ondanks wisselende competitieresultaten in staat bleef om in de knock-outfase van de beker het verschil te maken. Voor de supporters was het een welkome trofee in een periode zonder kampioenschappen.", diff:2 },

  "AJ017": { jaar:2007, cat:"Beker", renner:"Ajax", nat:"🇳🇱 Nederland", race:"KNVB Beker", kort:"Een bekerfinale tegen een ploeg uit Alkmaar wordt pas na een marathon aan strafschoppen beslist", lang:"Ajax veroverde de KNVB-beker dat jaar na een slopende strafschoppenreeks tegen AZ, die na een 1-1 gelijkspel in de reguliere speeltijd en verlenging pas bij 8-7 in de penalty's werd beslist. Het was een van de langste en meest dramatische bekerfinales in de Nederlandse voetbalgeschiedenis. Met een selectie in opbouw richting een nieuwe generatie bleek de beker een belangrijke troostprijs in een verder wisselvallig seizoen. De zenuwslopende ontknoping bleef nog jarenlang een gespreksonderwerp onder supporters.", diff:3 },

  "AJ018": { jaar:2010, cat:"Beker", renner:"Ajax", nat:"🇳🇱 Nederland", race:"KNVB Beker", kort:"In een bekerfinale over twee wedstrijden tegen de eeuwige rivaal uit Rotterdam wordt dubbel gescoord", lang:"Ajax pakte de KNVB-beker dat jaar in een tweeluik tegen aartsrivaal Feyenoord, met zeges van 2-0 en 4-1 over beide wedstrijden. De destijds nog gehanteerde opzet met een heen- en terugfinale zorgde voor een unieke reeks aan Amsterdam-Rotterdam-affiches in korte tijd. De ruime overwinningen onderstreepten de overmacht van Ajax op de rivaal in dat seizoen. Deze bekerwinst luidde bovendien een periode in waarin de club zich weer richting de absolute top van Nederland bewoog.", diff:2 },

  "AJ019": { jaar:2019, cat:"Beker", renner:"Erik ten Hag", nat:"🇳🇱 Nederland", race:"KNVB Beker", kort:"Een trainer pakt zijn allereerste prijs als hoofdtrainer tegen een ploeg uit Tilburg, als opmaat naar een historisch slot van het seizoen", lang:"Ajax won onder Erik ten Hag de KNVB-bekerfinale van dat seizoen van Willem II, de eerste prijs van de trainer sinds zijn aanstelling. Slechts enkele dagen later volgde ook de landstitel, waarmee de ploeg een binnenlandse dubbel completeerde. Het seizoen zou nog spectaculairder worden dankzij een historische Europese campagne die tot in de halve finale van de Champions League reikte. Deze bekerzege gold achteraf als het eerste puzzelstukje van wat een van de mooiste seizoenen uit de recente clubgeschiedenis zou worden.", diff:2 },

  "AJ020": { jaar:2021, cat:"Beker", renner:"Ajax", nat:"🇳🇱 Nederland", race:"KNVB Beker", kort:"Een twintigste bekerzege wordt in een spannende finale tegen een ploeg uit Arnhem behaald met een doelpunt verschil", lang:"Ajax won de KNVB-beker dat jaar met 2-1 van Vitesse en veroverde daarmee voor de twintigste keer de nationale beker, een record voor de club. De zege werd behaald in een fase waarin het Nederlandse voetbal nog altijd grotendeels zonder publiek werd gespeeld vanwege de coronapandemie. Deze bekerwinst bevestigde de status van Ajax als de meest succesvolle bekerclub van Nederland. Het seizoen zou uiteindelijk ook nog de landstitel opleveren, waarmee opnieuw een dubbel werd behaald.", diff:2 },

  "AJ021": { jaar:2019, cat:"Beker", renner:"Erik ten Hag", nat:"🇳🇱 Nederland", race:"Johan Cruijff Schaal", kort:"Het Nederlandse voetbalseizoen wordt geopend met een overtuigende zege op de landskampioen van het voorgaande jaar", lang:"Ajax opende dat seizoen met een 2-0 zege op PSV in de strijd om de Johan Cruijff Schaal, de traditionele seizoensopener tussen de landskampioen en de bekerwinnaar van het voorgaande jaar. Het was de laatste keer dat Erik ten Hag met Ajax een prijs veroverde in de Schaal, die de club in de voorgaande decennia al vaker had gewonnen. De zege gaf een vroeg signaal af over de vorm van de ploeg aan het begin van een seizoen dat uiteindelijk historisch zou worden. Voor de supporters was het een fraaie start van een onvergetelijke jaargang.", diff:3 },

  "AJ022": { jaar:1995, cat:"Europa", renner:"Patrick Kluivert", nat:"🇳🇱 Nederland", race:"UEFA Champions League", kort:"Een achttienjarige invaller schrijft geschiedenis met het enige doelpunt in een Europese eindstrijd tegen de titelverdediger uit Italië", lang:"Ajax werd dat jaar Europees kampioen door in de finale in Wenen met 1-0 te winnen van titelverdediger AC Milan. Invaller Patrick Kluivert, destijds nog maar achttien jaar oud, schoot vlak voor tijd de beslissende treffer binnen en werd daarmee de jongste doelpuntenmaker ooit in een Europacupfinale. Onder trainer Louis van Gaal speelde de ploeg met een basis van eigen jeugdproducten een aantrekkelijke en dominante stijl van voetbal. Deze zege gold als de bekroning van een van de beste generaties uit de Nederlandse clubvoetbalgeschiedenis.", diff:1 },

  "AJ023": { jaar:1995, cat:"Europa", renner:"Ajax", nat:"🇳🇱 Nederland", race:"UEFA Super Cup", kort:"Vers gekroond als Europees kampioen wordt ook de continentale supercup naar Amsterdam gehaald na een ruime thuiszege", lang:"Ajax veroverde dat jaar de UEFA Super Cup door in het tweeluik met Real Zaragoza in totaal met 5-1 te winnen, na een gelijkspel in Spanje gevolgd door een 4-0 zege in eigen huis. De prijs, uitgereikt tussen de winnaars van de Europacup I en de Europacup II, onderstreepte de sterke positie van de ploeg in Europa dat seizoen. Het was een van de vele trofeeën die de ploeg van Louis van Gaal in korte tijd bijeen wist te sprokkelen. Deze zege wordt tegenwoordig minder herinnerd dan de grote Europacupfinale zelf, maar bleef een unieke aanvulling op de erelijst.", diff:3 },

  "AJ024": { jaar:1995, cat:"Europa", renner:"Edwin van der Sar", nat:"🇳🇱 Nederland", race:"Intercontinental Cup", kort:"In een verre Aziatische stad wordt de wereldbeker voor clubteams via strafschoppen veroverd tegen de Zuid-Amerikaanse kampioen", lang:"Ajax werd dat jaar wereldkampioen voor clubteams door in Tokio met strafschoppen te winnen van het Braziliaanse Grêmio, na een doelpuntloze wedstrijd in reguliere speeltijd en verlenging. Doelman Edwin van der Sar hield een beslissende inzet uit de strafschoppenserie, waarna Ajax met 4-3 aan het langste eind trok. Het was de tweede keer in de clubgeschiedenis dat deze prijs werd gewonnen, na een eerdere triomf in de jaren zeventig. Deze zege completeerde een unieke reeks trofeeën voor de ploeg van Louis van Gaal in een van de beste seizoenen ooit.", diff:3 },

  "AJ025": { jaar:1996, cat:"Europa", renner:"Ajax", nat:"🇳🇱 Nederland", race:"UEFA Champions League", kort:"Na een onverwachte nederlaag in eigen huis wordt de halve finale alsnog overtuigend gekeerd met een ruime zege in Griekenland", lang:"Ajax bereikte dat jaar opnieuw de finale van de Champions League, nadat de ploeg in de halve finale eerst thuis met 0-1 verloor van het Griekse Panathinaikos. In de return in Athene draaide Ajax de achterstand echter volledig om met een overtuigende 3-0 zege, goed voor een 3-1 zege over twee wedstrijden. Deze comeback bevestigde dat de titelverdediger nog altijd tot de absolute Europese top behoorde. Het bracht de ploeg voor de tweede keer op rij naar de eindstrijd van het miljardenbal.", diff:3 },

  "AJ026": { jaar:1996, cat:"Europa", renner:"Ajax", nat:"🇳🇱 Nederland", race:"UEFA Champions League", kort:"De titelverdediger verliest de eindstrijd in de hoofdstad van Italië na strafschoppen tegen een ploeg uit Turijn", lang:"Ajax verloor dat jaar de finale van de Champions League van Juventus na strafschoppen, nadat de wedstrijd na negentig minuten en verlenging in 1-1 was geëindigd. In de beslissende reeks miste onder anderen Edgar Davids, waarna de Italianen hun kansen wel benutten en de trofee wonnen. Het betekende het einde van het Van Gaal-tijdperk als Europees kampioen, al bleef de ploeg nog altijd een van de sterkste van het continent. Kort na deze finale begon de generatie van 1995 langzaam uiteen te vallen door vertrekkende sterspelers.", diff:1 },

  "AJ027": { jaar:1997, cat:"Europa", renner:"Louis van Gaal", nat:"🇳🇱 Nederland", race:"UEFA Champions League", kort:"In zijn laatste Europese campagne als trainer wordt de ploeg in de halve finale uitgeschakeld door dezelfde Italiaanse club als het jaar ervoor", lang:"Ajax werd dat jaar in de halve finale van de Champions League uitgeschakeld door Juventus, dat na een nederlaag in Amsterdam in de return in Turijn met 4-1 won en zo met 5-2 over twee wedstrijden doorging. Het betekende voor de derde keer op rij een confrontatie met de Italiaanse club op het hoogste Europese niveau. Voor trainer Louis van Gaal was dit zijn laatste Europese campagne bij de club, voordat hij na dat seizoen naar Barcelona vertrok. Door het uiteenvallen van de succesvolle generatie zou het meer dan twintig jaar duren voordat Ajax weer zo ver in Europa zou komen.", diff:2 },

  "AJ028": { jaar:2003, cat:"Europa", renner:"Ajax", nat:"🇳🇱 Nederland", race:"UEFA Champions League", kort:"Een kwartfinale tegen een Italiaanse topclub wordt pas in de allerlaatste minuut in San Siro beslist", lang:"Ajax werd dat jaar in de kwartfinale van de Champions League uitgeschakeld door AC Milan, dat na een doelpuntloos gelijkspel in Amsterdam in San Siro pas in de absolute slotfase de beslissende treffer maakte voor een 3-2 zege. Milan zou het toernooi dat seizoen uiteindelijk winnen, wat de kwaliteit van de tegenstander onderstreepte. Voor Ajax bleek dit lange tijd de laatste Europese kwartfinale, in een periode waarin de club het internationaal moeilijker kreeg. Pas jaren later zou de ploeg weer zo ver in de Champions League doordringen.", diff:3 },

  "AJ029": { jaar:2017, cat:"Europa", renner:"Peter Bosz", nat:"🇳🇱 Nederland", race:"UEFA Europa League", kort:"Een jonge ploeg onder een debuterende trainer bereikt verrassend een Europese eindstrijd in Zweden, maar moet daar een Engelse topclub voor zich dulden", lang:"Ajax bereikte dat jaar onder de kersverse trainer Peter Bosz de finale van de Europa League, maar verloor in Stockholm met 2-0 van Manchester United. Op weg naar de finale had de jonge ploeg met onder anderen Davy Klaassen en Kasper Dolberg meerdere gerenommeerde tegenstanders uitgeschakeld. Ondanks het verlies gold het toernooi als een belangrijke stap in de wederopbouw van de club na jaren zonder Europees succes. Veel spelers uit deze lichting zouden kort daarna voor veel geld naar het buitenland vertrekken.", diff:2 },

  "AJ030": { jaar:2019, cat:"Europa", renner:"Ajax", nat:"🇳🇱 Nederland", race:"UEFA Champions League", kort:"De regerend recordkampioen wordt in diens eigen stadion in Spanje met een ruime marge naar huis gestuurd", lang:"Ajax versloeg dat jaar Real Madrid in de achtste finale van de Champions League met 4-1 in het Santiago Bernabéu, na een 2-1 zege in de heenwedstrijd in Amsterdam. Doelpunten van onder anderen Hakim Ziyech, David Neres en Dusan Tadic zorgden voor de zwaarste thuisnederlaag ooit voor de Spaanse club in een Europese wedstrijd. Deze uitschakeling van de titelverdediger zorgde voor wereldwijde verbazing en gaf de jonge ploeg van Erik ten Hag internationaal aanzien. Het was de opmaat naar een van de meest bijzondere Europese campagnes in de clubgeschiedenis.", diff:1 },

  "AJ031": { jaar:2019, cat:"Europa", renner:"Matthijs de Ligt", nat:"🇳🇱 Nederland", race:"UEFA Champions League", kort:"Een negentienjarige aanvoerder kopt zijn ploeg in Turijn naar de halve finale nadat een sterspeler zijn ploeg eerder op voorsprong had gezet", lang:"Ajax schakelde dat jaar Juventus uit in de kwartfinale van de Champions League, met een beslissende kopbal van de negentienjarige aanvoerder Matthijs de Ligt in Turijn. Cristiano Ronaldo had de Italianen eerder in de wedstrijd op voorsprong gekopt, maar Donny van de Beek en later De Ligt zorgden voor een 2-1 zege op de avond en 3-2 over twee wedstrijden. Hiermee bereikte Ajax voor het eerst sinds het seizoen van de halve finale tegen Juventus in de jaren negentig weer de laatste vier van het miljardenbal. De prestatie maakte wereldwijd indruk en zette de jonge Nederlandse verdediger definitief op de kaart.", diff:1 },

  "AJ032": { jaar:2019, cat:"Europa", renner:"Ajax", nat:"🇳🇱 Nederland", race:"UEFA Champions League", kort:"Een 2-0 voorsprong bij rust in eigen huis wordt in de tweede helft door een Braziliaanse invaller in extremis onderuitgehaald", lang:"Ajax leek dat jaar op weg naar de finale van de Champions League na doelpunten van Matthijs de Ligt en Hakim Ziyech, die de ploeg bij rust op een 2-0 voorsprong en 3-0 op aggregaat zetten tegen Tottenham Hotspur. In de tweede helft maakte de Braziliaanse invaller Lucas Moura echter een hattrick, met de beslissende treffer diep in blessuretijd, waardoor de Engelse club alsnog op uitdoelpunten doorging. Het betekende een van de meest dramatische uitschakelingen uit de Europese clubvoetbalgeschiedenis. Voor de jonge ploeg van Erik ten Hag bleef desondanks een historisch seizoen over, met de landstitel en beker als troost.", diff:1 },

  "AJ033": { jaar:2021, cat:"Europa", renner:"Sébastien Haller", nat:"🇨🇮 Ivoorkust", race:"UEFA Champions League", kort:"Een spits scoort in elk van zijn eerste groepswedstrijden en verbreekt daarmee een langlopend record in het miljardenbal", lang:"Sébastien Haller scoorde dat jaar in al zijn eerste zes groepswedstrijden in de Champions League voor Ajax, goed voor tien doelpunten en daarmee een nieuw record voor de snelste tien treffers ooit in het toernooi. Zijn debuutwedstrijd leverde direct vier doelpunten op tegen Sporting Lissabon, een prestatie die sinds Marco van Basten in de jaren negentig niemand meer had laten zien. Ajax werd dat seizoen ongeslagen groepswinnaar, een zeldzame prestatie in de sterk bezette groepsfase. Haller groeide in korte tijd uit tot een van de meest besproken aanvallers van het Europese seizoen.", diff:2 },

  "AJ034": { jaar:2022, cat:"Europa", renner:"Ajax", nat:"🇳🇱 Nederland", race:"UEFA Champions League", kort:"In een zware groep met Engelse en Italiaanse tegenstand wordt tegen de zwakste tegenstander dubbel gewonnen, maar dat blijkt niet genoeg", lang:"Ajax werd dat seizoen uitgeschakeld in de groepsfase van de Champions League, in een zware poule met Liverpool, Napoli en Rangers. Tegen Rangers werd nog dubbel gewonnen, met een 4-0 zege thuis en een zege in Schotland, maar tegen zowel Napoli als Liverpool ging het mis, met onder meer een pijnlijke 1-6 nederlaag thuis tegen de Italianen. Trainer Alfred Schreuder erkende na afloop dat beide tegenstanders een maatje te groot waren gebleken. De vroege uitschakeling zette de toon voor een moeizamer decennium in Europa na de gloriejaren onder Erik ten Hag.", diff:3 },

  "AJ035": { jaar:1996, cat:"Icoon", renner:"Edgar Davids", nat:"🇳🇱 Nederland", race:"Transfer", kort:"Twee jonge verdedigers van de Europese kampioen vertrekken transfervrij naar Italië dankzij een baanbrekende juridische uitspraak", lang:"Edgar Davids en Michael Reiziger verlieten dat jaar Ajax transfervrij richting AC Milan, een directe consequentie van het net daarvoor gewezen Bosman-arrest. Clubs hoefden voortaan geen transfersom meer te betalen voor spelers van wie het contract was afgelopen, waardoor buitenlandse topclubs de kampioensploeg van Ajax met hogere salarissen konden weglokken. Het vertrek van deze twee sleutelspelers markeerde het begin van het uiteenvallen van de gouden generatie van trainer Louis van Gaal. Binnen twee jaar zouden nog meer sterspelers uit die ploeg de club verlaten.", diff:2 },

  "AJ036": { jaar:1997, cat:"Icoon", renner:"Patrick Kluivert", nat:"🇳🇱 Nederland", race:"Transfer", kort:"De held van de Europese eindstrijd van twee jaar eerder verruilt Amsterdam voor Milaan, samen met een verdediger uit dezelfde lichting", lang:"Patrick Kluivert, de matchwinner van de Champions League-finale van 1995, vertrok dat jaar naar AC Milan, net als zijn ploeggenoot Winston Bogarde. Het vertrek van Kluivert gold als een van de meest pijnlijke verliezen voor de club, aangezien hij als jeugdproduct symbool stond voor de succesvolle generatie van Louis van Gaal. Door het Bosman-arrest konden clubs als Milan dit soort transfers steeds vaker transfervrij of tegen relatief lage bedragen realiseren. Met dit vertrek was de gouden ploeg van 1995 nog maar een schim van zichzelf.", diff:2 },

  "AJ037": { jaar:1997, cat:"Icoon", renner:"Marc Overmars", nat:"🇳🇱 Nederland", race:"Transfer", kort:"Een snelle buitenspeler met een verwoestende sprint verruilt de Nederlandse hoofdstad voor Noord-Londen", lang:"Marc Overmars vertrok dat jaar naar Arsenal, waar hij onder trainer Arsène Wenger uitgroeide tot een van de sleutelspelers van de Engelse club. Bij Ajax was Overmars een vaste waarde geweest in de kampioensploegen van het Van Gaal-tijdperk, bekend om zijn explosieve snelheid over de rechterflank. Zijn vertrek, kort na dat van andere sterspelers, bevestigde dat de gouden generatie definitief uit elkaar aan het vallen was. Overmars zou jaren later als bestuurder nog terugkeren in de Nederlandse voetbalwereld, ook bij Ajax zelf.", diff:2 },

  "AJ038": { jaar:1996, cat:"Icoon", renner:"Ajax", nat:"🇳🇱 Nederland", race:"Stadion", kort:"Een gloednieuw en destijds futuristisch stadion met een schuifdak wordt door de koningin geopend met een openingswedstrijd tegen een Italiaanse topclub", lang:"Ajax verruilde dat jaar het oude De Meer-stadion voor een nieuw, groot stadion aan de rand van Amsterdam, dat werd geopend door koningin Beatrix. De openingswedstrijd tegen AC Milan ging met 3-0 verloren, maar het stadion zelf gold als revolutionair dankzij het sluitbare dak, destijds een noviteit in Europa. Het complex zou uitgroeien tot het decor van vrijwel alle grote thuiswedstrijden van de club in de decennia erna. Pas jaren later kreeg het stadion de naam van de grootste clublegende ooit.", diff:2 },

  "AJ039": { jaar:1998, cat:"Icoon", renner:"Ajax", nat:"🇳🇱 Nederland", race:"Beursgang", kort:"Als eerste voetbalclub van Nederland worden aandelen van de club te koop aangeboden op de effectenbeurs", lang:"Ajax ging dat jaar als eerste en tot op heden enige Nederlandse voetbalclub naar de beurs, met een introductiekoers die destijds op 32,50 gulden per aandeel werd vastgesteld. De beursgang leverde de club omgerekend ongeveer 54 miljoen euro op, geld dat werd gebruikt voor spelers en infrastructuur. Achteraf bleek de beursgang minder op te leveren dan analisten vooraf hadden verwacht. Toch bleef Ajax hierdoor decennialang de enige beursgenoteerde profclub van het land, een unieke positie in het Nederlandse voetbal.", diff:3 },

  "AJ040": { jaar:1999, cat:"Icoon", renner:"Frank de Boer", nat:"🇳🇱 Nederland", race:"Transfer", kort:"Twee tweelingbroers die jarenlang het hart van de ploeg vormden, vertrekken na een slepend contractconflict gezamenlijk naar Catalonië", lang:"Frank en Ronald de Boer vertrokken dat jaar samen naar FC Barcelona, na een langslepend conflict met de clubleiding over een eerder getekende contractverlenging. De tweelingbroers hadden jarenlang de ruggengraat van het elftal gevormd, met Frank als verdediger en Ronald als aanvallende middenvelder. Bij Barcelona voegden zij zich bij hun oud-trainer Louis van Gaal, die daar inmiddels aan de slag was. Hun vertrek betekende het definitieve einde van de laatste restanten van de gouden generatie van de jaren negentig.", diff:2 },

  "AJ041": { jaar:1999, cat:"Icoon", renner:"Edwin van der Sar", nat:"🇳🇱 Nederland", race:"Transfer", kort:"Een doelman die negen seizoenen tussen de palen stond en Europees kampioen werd, vertrekt naar Turijn", lang:"Edwin van der Sar verliet dat jaar Ajax na negen seizoenen, waarin hij uitgroeide tot een van de beste doelmannen van Europa en in 1995 Champions League-winnaar werd. Bij Juventus werd hij de eerste buitenlandse keeper ooit in de historie van de Italiaanse club en speelde hij twee seizoenen op het hoogste niveau. Later zou Van der Sar via Fulham nog naar Manchester United vertrekken, waar hij zijn carrière op recordhoogte afsloot. Tientallen jaren later keerde hij terug bij Ajax, ditmaal als bestuurder in plaats van speler.", diff:2 },

  "AJ042": { jaar:2001, cat:"Icoon", renner:"Zlatan Ibrahimović", nat:"🇸🇪 Zweden", race:"Transfer", kort:"Een negentienjarige Zweedse spits met een uitzonderlijke techniek arriveert vanuit Scandinavië en groeit al snel uit tot publiekslieveling", lang:"Zlatan Ibrahimović tekende dat jaar bij Ajax, overgekomen van het Zweedse Malmö FF voor een bedrag van destijds ongeveer 8,7 miljoen euro. De jonge spits imponeerde al snel met zijn techniek en zelfvertrouwen, en werd een sleutelfiguur in het team van trainer Ronald Koeman. Met opvallende acties, waaronder later een veelbesproken solo-doelpunt tegen NAC Breda, groeide hij razendsnel uit tot een van de meest besproken talenten van Europa. Zijn tijd bij Ajax legde de basis voor een van de meest kleurrijke carrières in de recente voetbalgeschiedenis.", diff:2 },

  "AJ043": { jaar:2003, cat:"Icoon", renner:"Wesley Sneijder", nat:"🇳🇱 Nederland", race:"Transfer", kort:"Een jeugdproduct met een uitstekend linkerbeen maakt op negentienjarige leeftijd zijn officiële debuut in een ruime overwinning", lang:"Wesley Sneijder maakte dat jaar zijn officiële debuut voor Ajax in een 6-0 zege op Willem II, na jarenlang te zijn opgeleid in de eigen jeugdopleiding. Zijn techniek en balgevoel vielen direct op, en al snel werd hij bekroond met de Johan Cruijff Prijs voor beste jeugdspeler van Nederland. In de jaren erna groeide Sneijder uit tot een onmisbare schakel in het Ajax-elftal en een vaste waarde bij het Nederlands elftal. Zijn opkomst gold als bewijs dat de jeugdopleiding van de club ook na de gouden generatie van de jaren negentig nieuwe sterspelers bleef voortbrengen.", diff:2 },

  "AJ044": { jaar:2004, cat:"Icoon", renner:"Zlatan Ibrahimović", nat:"🇸🇪 Zweden", race:"Transfer", kort:"Een spits die drie jaar eerder als tiener arriveerde, vertrekt na oplopende spanningen op de laatste dag van de transfermarkt naar Turijn", lang:"Zlatan Ibrahimović vertrok dat jaar op de slotdag van de transfermarkt naar Juventus, voor een bedrag van destijds ongeveer 16 miljoen euro. Zijn laatste periode bij Ajax werd overschaduwd door spanningen binnen de selectie en met de clubleiding. Toch had hij zich in drie seizoenen ontwikkeld tot een van de meest getalenteerde spitsen van Europa, met spraakmmakende individuele acties. Na Juventus zou Ibrahimović nog jarenlang tot de absolute wereldtop blijven behoren bij een reeks Europese topclubs.", diff:2 },

  "AJ045": { jaar:2005, cat:"Icoon", renner:"Rafael van der Vaart", nat:"🇳🇱 Nederland", race:"Transfer", kort:"Een technisch begaafde aanvallende middenvelder en voormalig aanvoerder verruilt de Eredivisie voor de Bundesliga", lang:"Rafael van der Vaart vertrok dat jaar naar Hamburger SV, voor een bedrag van ongeveer 5,5 miljoen euro. Als jeugdproduct van de club had hij zich ontwikkeld tot een creatieve aanvallende middenvelder en droeg hij zelfs een periode de aanvoerdersband. Bij Hamburg werd hij direct clubtopscorer en hielp hij de Duitse club aan Europees voetbal. Zijn vertrek paste in een patroon waarbij Ajax steeds vaker zijn beste talenten na een aantal seizoenen aan buitenlandse topcompetities verloor.", diff:3 },

  "AJ046": { jaar:2007, cat:"Icoon", renner:"Wesley Sneijder", nat:"🇳🇱 Nederland", race:"Transfer", kort:"Een middenvelder die als tiener debuteerde en inmiddels topscorer van het seizoen was, verruilt Amsterdam voor de Spaanse hoofdstad", lang:"Wesley Sneijder vertrok dat jaar naar Real Madrid voor ongeveer 27 miljoen euro, destijds een van de hoogste transferbedragen ooit voor een Nederlandse speler. In zijn laatste seizoen bij Ajax was hij met achttien competitietreffers een van de absolute uitblinkers van de Eredivisie geweest. Bij Real Madrid won hij meteen in zijn eerste seizoen de Spaanse landstitel. Sneijders vertrek onderstreepte de rol van de Ajax-jeugdopleiding als kweekvijver voor spelers die later bij Europese topclubs zouden schitteren.", diff:2 },

  "AJ047": { jaar:2011, cat:"Icoon", renner:"Luis Suárez", nat:"🇺🇾 Uruguay", race:"Transfer", kort:"Een doelpuntenmachine die jarenlang de aanval droeg, vertrekt midden in het seizoen naar de Premier League voor een clubrecordbedrag", lang:"Luis Suárez vertrok dat jaar naar Liverpool voor ongeveer 26,5 miljoen euro, destijds het duurste vertrek van een Ajax-speler ooit. In zijn tijd bij de club groeide hij uit tot een van de dodelijkste afmakers van Europa, met een sterk vormend duo samen met Klaas-Jan Huntelaar. Zijn vertrek kwam midden in het seizoen waarin Ajax onder Frank de Boer op weg was naar de landstitel. Bij Liverpool en later Barcelona zou Suárez uitgroeien tot een van de beste spitsen van zijn generatie wereldwijd.", diff:2 },

  "AJ048": { jaar:2013, cat:"Icoon", renner:"Christian Eriksen", nat:"🇩🇰 Denemarken", race:"Transfer", kort:"Een Deense middenvelder die op zeventienjarige leeftijd debuteerde, kiest na jaren als creatieve spelmaker voor een avontuur in Londen", lang:"Christian Eriksen vertrok dat jaar naar Tottenham Hotspur, na als zestienjarige door Ajax te zijn weggeplukt uit Denemarken en zich te hebben ontwikkeld tot een van de beste passgevers van de competitie. In zijn tijd bij Ajax werd hij uitgeroepen tot Nederlands talent van het jaar en won hij meerdere landstitels. Bij Tottenham groeide hij uit tot een sleutelspeler en later een van de beste Premier League-middenvelders van zijn tijd. Zijn vertrek paste in het steeds terugkerende patroon van talentvolle Ajax-spelers die na hun doorbraak naar een grotere competitie vertrokken.", diff:3 },

  "AJ049": { jaar:2014, cat:"Icoon", renner:"Daley Blind", nat:"🇳🇱 Nederland", race:"Transfer", kort:"Een veelzijdige verdediger die net met Oranje een uitstekend WK speelde, verruilt Amsterdam voor Manchester", lang:"Daley Blind vertrok dat jaar naar Manchester United voor ongeveer 13,8 miljoen euro, kort na een sterk WK met het Nederlands elftal. Als jeugdproduct van Ajax had hij een sleutelrol gespeeld in de vier landstitels op rij onder trainer Frank de Boer. Bij Manchester United won hij in de jaren erna onder meer de FA Cup en de Europa League. Jaren later zou Blind terugkeren bij Ajax, het eerste van meerdere keren dat hij de club weer zou vervoegen na een avontuur elders.", diff:2 },

  "AJ050": { jaar:2016, cat:"Icoon", renner:"Johan Cruijff", nat:"🇳🇱 Nederland", race:"Overlijden", kort:"De grootste clublegende ooit, wiens visie op voetbal decennialang de identiteit van de club bepaalde, overlijdt na een ziekbed", lang:"Johan Cruijff overleed dat jaar aan de gevolgen van longkanker, tot verdriet van de gehele voetbalwereld en in het bijzonder van Ajax, de club waar hij als speler drie keer de Europacup I won en later als trainer en bestuurder zijn stempel drukte. Zijn visie op aanvallend, positiespel bleef decennialang de basis van de opleiding en speelstijl van de club. Kort na zijn overlijden werd besloten om het thuisstadion van Ajax naar hem te vernoemen, wat twee seizoenen later werd doorgevoerd. Zijn erfenis bleef voortleven in de vele generaties spelers die via de jeugdopleiding met zijn ideeën werden grootgebracht.", diff:1 },

  "AJ051": { jaar:2017, cat:"Icoon", renner:"Davy Klaassen", nat:"🇳🇱 Nederland", race:"Transfer", kort:"Een aanvoerder die zijn ploeg naar een Europese finale leidde, vertrekt kort na dat seizoen naar Engeland", lang:"Davy Klaassen vertrok dat jaar naar Everton voor ongeveer 27 miljoen euro, kort nadat hij als aanvoerder Ajax naar de finale van de Europa League had geleid. In dat bewuste Europese seizoen was hij goed voor belangrijke doelpunten, onder meer tegen Schalke 04 in de kwartfinale. Bij Ajax had hij zich via de jeugdopleiding ontwikkeld tot een complete middenvelder met een neus voor de goal. Zijn vertrek was onderdeel van een grotere uittocht van spelers uit de ploeg die net nog de Europese finale had gehaald.", diff:3 },

  "AJ052": { jaar:2019, cat:"Icoon", renner:"Matthijs de Ligt", nat:"🇳🇱 Nederland", race:"Transfer", kort:"De jongste aanvoerder in de clubgeschiedenis, die zijn ploeg naar een historische Europese halve finale loodste, vertrekt voor een clubrecordbedrag naar Italië", lang:"Matthijs de Ligt vertrok dat jaar naar Juventus voor ongeveer 75 miljoen euro, een recordbedrag voor een uitgaande Ajax-transfer op dat moment. Als negentienjarige aanvoerder had hij dat seizoen een hoofdrol gespeeld in de historische Europese campagne die tot de halve finale van de Champions League reikte. Bij Ajax was hij op zeventienjarige leeftijd al de jongste aanvoerder ooit van de club geworden. Zijn vertrek markeerde het begin van het uiteenvallen van de succesvolle ploeg van Erik ten Hag, nadat meerdere sterspelers dat seizoen internationaal furore hadden gemaakt.", diff:1 },

  "AJ053": { jaar:2019, cat:"Icoon", renner:"Frenkie de Jong", nat:"🇳🇱 Nederland", race:"Transfer", kort:"Een balvaste middenvelder die voor een symbolisch bedrag uit de jeugdopleiding van een andere club kwam, vertrekt na één uitzonderlijk seizoen voor tientallen miljoenen naar Catalonië", lang:"Frenkie de Jong vertrok dat jaar naar FC Barcelona voor ongeveer 75 miljoen euro, nadat hij enkele jaren eerder voor een symbolisch bedrag van Willem II naar Ajax was gekomen. In zijn laatste seizoen werd hij uitgeroepen tot Speler van het Jaar in de Eredivisie en speelde hij een sleutelrol in de historische Europese campagne van dat seizoen. Zijn rustige balbezit en passing herinnerden veel supporters aan het Cruijffiaanse spelidee waar de club om bekendstond. Samen met het vertrek van De Ligt zorgde deze transfer voor een grote aderlating in de ploeg die net nog de halve finale van de Champions League had gehaald.", diff:1 },

  "AJ054": { jaar:2020, cat:"Icoon", renner:"Hakim Ziyech", nat:"🇲🇦 Marokko", race:"Transfer", kort:"Een Marokkaanse spelmaker die met een schitterend doelpunt in Madrid furore maakte, vertrekt naar Londen", lang:"Hakim Ziyech vertrok dat jaar naar Chelsea voor een bedrag van ongeveer 40 miljoen euro, na jarenlang met zijn linkerbeen en scherpe voorzetten het spel van Ajax te hebben bepaald. Hij was een van de smaakmakers van de historische Europese campagne van het seizoen daarvoor, onder meer met een treffer in de zwaarbevochten uitzege op Real Madrid. Bij Chelsea moest hij wennen aan een kleinere rol, ondanks zijn eerdere status als een van de meest gevreesde aanvallers van de Eredivisie. Zijn vertrek was onderdeel van de uittocht van spelers uit de generatie die Ajax naar de halve finale van de Champions League had geleid.", diff:2 },

  "AJ055": { jaar:2022, cat:"Icoon", renner:"Antony", nat:"🇧🇷 Brazilië", race:"Transfer", kort:"Een dribbelende Braziliaanse buitenspeler vertrekt voor een recordbedrag naar Engeland, waarmee hij de duurste uitgaande transfer in de geschiedenis van de Eredivisie wordt", lang:"Antony vertrok dat jaar naar Manchester United voor een bedrag tot ongeveer 100 miljoen euro, wat hem de duurste speler ooit maakte die de Eredivisie verliet. Bij Ajax had de Braziliaanse buitenspeler zich in twee seizoenen ontwikkeld tot een onvoorspelbare dribbelaar die regelmatig besliste in de slotfase van wedstrijden. Zijn vertrek volgde op het seizoen waarin Ajax onder Erik ten Hag voor de derde keer in vier jaar landskampioen werd. Het recordbedrag onderstreepte de blijvende reputatie van de club als leverancier van aanvallend toptalent aan de Europese top.", diff:2 },

  "AJ056": { jaar:2022, cat:"Icoon", renner:"Marc Overmars", nat:"🇳🇱 Nederland", race:"Bestuurscrisis", kort:"Een voormalige clubheld die als bestuurder jarenlang het transferbeleid bepaalde, vertrekt abrupt na berichten over grensoverschrijdend gedrag", lang:"Marc Overmars vertrok dat jaar per direct als directeur voetbalzaken bij Ajax, nadat bekend werd dat hij gedurende langere tijd grensoverschrijdende berichten had gestuurd naar meerdere vrouwelijke collega's. Overmars, die als speler in de jaren negentig een clubicoon was geweest, had als bestuurder een centrale rol gespeeld in het spelersbeleid dat de club terugbracht naar de Europese subtop. Later werd hij door de tuchtcommissie van de sport voor in totaal twee jaar geschorst, waarvan een deel voorwaardelijk. Zijn vertrek zorgde voor grote onrust binnen de clubleiding, kort na een succesvol sportief seizoen.", diff:2 },

  "AJ057": { jaar:2023, cat:"Icoon", renner:"Maurice Steijn", nat:"🇳🇱 Nederland", race:"Eredivisie", kort:"Een kersverse trainer wordt na een historisch slechte competitiestart alweer na enkele maanden ontslagen", lang:"Maurice Steijn werd dat jaar ontslagen als trainer van Ajax na een van de slechtste competitiestarts in de recente clubgeschiedenis, met slechts één overwinning uit de eerste zeven competitiewedstrijden. Het seizoen zou uiteindelijk uitmonden in de op een na slechtste eindklassering van Ajax ooit, met een recordachterstand van negenentwintig punten op koploper PSV. Onder de daaropvolgende interim-trainer John van 't Schip werd de rest van het seizoen enigszins gestabiliseerd, met Europees voetbal als uiteindelijk doel. Deze roerige periode symboliseerde de neergang van de club in de jaren na het vertrek van Erik ten Hag naar Manchester United.", diff:3 },
};
